/**
 * @module idea-bridge/ticket-providers
 *
 * Pluggable ticket provider adapters for creating issues in
 * GitHub Issues, Jira, Linear, and Notion from implementation plans.
 * Each adapter generates properly formatted tickets with acceptance criteria.
 */

import { randomUUID } from "node:crypto";
import { z } from "zod";
import { generateText, extractJson } from "../copilot/client.js";
import { withRetry } from "../copilot/retry.js";
import { wrapUserInput, sanitizeLlmOutput } from "../prompts/sanitize.js";
import type {
  ImplementationTask,
  ImplementationPlan,
  PRD,
  CreatedIssue,
  IssueProvider,
  BridgeConfig,
} from "./types.js";

// ---- Acceptance Criteria Generation ----

const AcceptanceCriteriaResponseSchema = z.object({
  criteria: z
    .array(
      z.object({
        given: z.string().max(500),
        when: z.string().max(500),
        then: z.string().max(500),
      })
    )
    .max(10),
  definition_of_done: z.array(z.string().max(300)).max(8),
});

export type AcceptanceCriteria = z.infer<typeof AcceptanceCriteriaResponseSchema>;

/**
 * Generate structured acceptance criteria for a task using the LLM.
 */
export async function generateAcceptanceCriteria(
  task: ImplementationTask,
  prd: PRD,
  config: BridgeConfig = {}
): Promise<AcceptanceCriteria> {
  const relatedStory = prd.userStories.find((s) => s.id === task.storyId);
  const storyContext = relatedStory
    ? `\nRelated User Story: ${relatedStory.title}\nPersona: ${relatedStory.persona}`
    : "";

  const prompt = `Generate acceptance criteria for this implementation task.

Task: ${wrapUserInput("TASK", `${task.title}\n${task.description}`)}
Type: ${task.type}
${storyContext}
Project Goals: ${prd.goals.join(", ")}

Generate Gherkin-style acceptance criteria (Given/When/Then) and a Definition of Done checklist.

Respond in JSON:
{
  "criteria": [
    { "given": "initial state", "when": "action taken", "then": "expected result" }
  ],
  "definition_of_done": ["Unit tests pass", "Code reviewed", "Documentation updated"]
}`;

  return withRetry(
    async () => {
      const raw = await generateText({
        prompt,
        model: config.model,
        signal: config.signal,
      });
      return AcceptanceCriteriaResponseSchema.parse(
        JSON.parse(extractJson(sanitizeLlmOutput(raw)))
      );
    },
    { signal: config.signal }
  );
}

// ---- Ticket Body Formatters ----

/** Format acceptance criteria as markdown for ticket bodies. */
export function formatAcceptanceCriteriaMarkdown(ac: AcceptanceCriteria): string {
  const lines: string[] = ["## Acceptance Criteria\n"];
  for (const c of ac.criteria) {
    lines.push(`- **Given** ${c.given}`);
    lines.push(`  **When** ${c.when}`);
    lines.push(`  **Then** ${c.then}`);
    lines.push("");
  }
  if (ac.definition_of_done.length > 0) {
    lines.push("## Definition of Done\n");
    for (const item of ac.definition_of_done) {
      lines.push(`- [ ] ${item}`);
    }
  }
  return lines.join("\n");
}

// ---- Provider-Specific Formatters ----

export interface TicketPayload {
  title: string;
  body: string;
  labels: string[];
  milestone?: string;
  assignee?: string;
  priority?: string;
  estimate?: number;
  parentId?: string;
}

/** Format a task as a GitHub Issues-compatible ticket. */
export function formatGitHubTicket(
  task: ImplementationTask,
  ac: AcceptanceCriteria,
  prd: PRD,
  config: BridgeConfig = {}
): TicketPayload {
  const body = [
    `## Description\n`,
    task.description,
    "",
    formatAcceptanceCriteriaMarkdown(ac),
    "",
    `## Context`,
    "",
    `**PRD:** ${prd.title}`,
    `**Type:** ${task.type}`,
    `**Estimated Hours:** ${task.estimatedHours}`,
    task.dependencies.length > 0 ? `**Dependencies:** ${task.dependencies.join(", ")}` : "",
    "",
    task.scaffoldFiles?.length
      ? `## Scaffold Files\n\n${task.scaffoldFiles.map((f) => `- \`${f}\``).join("\n")}`
      : "",
    "",
    `---\n*Generated by Innovator Idea-to-Ticket Pipeline*`,
  ]
    .filter(Boolean)
    .join("\n");

  return {
    title: `[${task.type.toUpperCase()}] ${task.title}`,
    body,
    labels: [...(config.defaultLabels ?? []), ...task.labels, `type:${task.type}`],
    milestone: task.milestone ?? config.defaultMilestone,
    assignee: task.assignee,
    estimate: task.estimatedHours,
  };
}

/** Format a task as a Jira-compatible ticket. */
export function formatJiraTicket(
  task: ImplementationTask,
  ac: AcceptanceCriteria,
  prd: PRD,
  config: BridgeConfig = {}
): TicketPayload {
  const _typeMap: Record<string, string> = {
    feature: "Story",
    bug: "Bug",
    chore: "Task",
    spike: "Spike",
    test: "Task",
  };

  const body = [
    `h2. Description`,
    "",
    task.description,
    "",
    `h2. Acceptance Criteria`,
    "",
    ...ac.criteria.map((c) => `* *Given* ${c.given}\n** *When* ${c.when}\n** *Then* ${c.then}`),
    "",
    `h2. Definition of Done`,
    "",
    ...ac.definition_of_done.map((d) => `* ${d}`),
    "",
    `h2. Technical Details`,
    "",
    `*PRD:* ${prd.title}`,
    `*Estimated Hours:* ${task.estimatedHours}`,
    task.scaffoldFiles?.length
      ? `*Scaffold Files:*\n${task.scaffoldFiles.map((f) => `* {{${f}}}`).join("\n")}`
      : "",
  ]
    .filter(Boolean)
    .join("\n");

  return {
    title: task.title,
    body,
    labels: [...(config.defaultLabels ?? []), ...task.labels],
    milestone: task.milestone ?? config.defaultMilestone,
    assignee: task.assignee,
    priority: task.type === "bug" ? "High" : "Medium",
    estimate: task.estimatedHours,
  };
}

/** Format a task as a Linear-compatible ticket. */
export function formatLinearTicket(
  task: ImplementationTask,
  ac: AcceptanceCriteria,
  prd: PRD,
  config: BridgeConfig = {}
): TicketPayload {
  const body = [
    `## Description\n`,
    task.description,
    "",
    formatAcceptanceCriteriaMarkdown(ac),
    "",
    `**PRD:** ${prd.title}`,
    `**Estimated Hours:** ${task.estimatedHours}`,
    task.scaffoldFiles?.length
      ? `\n## Files to Create\n\n${task.scaffoldFiles.map((f) => `- \`${f}\``).join("\n")}`
      : "",
  ]
    .filter(Boolean)
    .join("\n");

  const priorityMap: Record<string, string> = {
    feature: "Medium",
    bug: "High",
    chore: "Low",
    spike: "Medium",
    test: "Low",
  };

  return {
    title: task.title,
    body,
    labels: [...(config.defaultLabels ?? []), ...task.labels],
    milestone: task.milestone ?? config.defaultMilestone,
    assignee: task.assignee,
    priority: priorityMap[task.type] ?? "Medium",
    estimate: task.estimatedHours,
  };
}

// ---- Batch Ticket Generation ----

export interface TicketBatch {
  provider: IssueProvider;
  tickets: Array<{
    taskId: string;
    payload: TicketPayload;
    acceptanceCriteria: AcceptanceCriteria;
  }>;
  summary: TicketBatchSummary;
}

export interface TicketBatchSummary {
  totalTickets: number;
  byType: Record<string, number>;
  totalEstimatedHours: number;
  phases: string[];
}

/**
 * Generate a complete batch of tickets with acceptance criteria
 * from an implementation plan and PRD.
 */
export async function generateTicketBatch(
  plan: ImplementationPlan,
  prd: PRD,
  config: BridgeConfig = {}
): Promise<TicketBatch> {
  const provider = config.issueProvider ?? "github";
  const formatFn =
    provider === "jira"
      ? formatJiraTicket
      : provider === "linear"
        ? formatLinearTicket
        : formatGitHubTicket;

  const tickets: TicketBatch["tickets"] = [];

  for (const task of plan.tasks) {
    if (config.signal?.aborted) break;

    const ac = await generateAcceptanceCriteria(task, prd, config);
    const payload = formatFn(task, ac, prd, config);

    tickets.push({
      taskId: task.id,
      payload,
      acceptanceCriteria: ac,
    });
  }

  const byType: Record<string, number> = {};
  for (const task of plan.tasks) {
    byType[task.type] = (byType[task.type] ?? 0) + 1;
  }

  return {
    provider,
    tickets,
    summary: {
      totalTickets: tickets.length,
      byType,
      totalEstimatedHours: plan.totalEstimatedHours,
      phases: plan.phases.map((p) => p.name),
    },
  };
}

/**
 * Convert a ticket batch to a set of CreatedIssue records
 * with local placeholder URLs (for preview before actual API calls).
 */
export function ticketBatchToCreatedIssues(
  batch: TicketBatch,
  config: BridgeConfig = {}
): CreatedIssue[] {
  const baseUrl =
    batch.provider === "github"
      ? `https://github.com/${config.repoOwner ?? "owner"}/${config.repoName ?? "repo"}/issues`
      : batch.provider === "jira"
        ? `https://jira.atlassian.net/browse`
        : batch.provider === "linear"
          ? `https://linear.app/team/issue`
          : `https://notion.so`;

  return batch.tickets.map((t, i) => ({
    id: `issue-${randomUUID().slice(0, 8)}`,
    taskId: t.taskId,
    provider: batch.provider,
    externalId: `#${i + 1}`,
    externalUrl: `${baseUrl}/${i + 1}`,
    title: t.payload.title,
    labels: t.payload.labels,
    milestone: t.payload.milestone,
    assignee: t.payload.assignee,
    createdAt: new Date().toISOString(),
  }));
}

/** Format the entire ticket batch as markdown for preview. */
export function ticketBatchToMarkdown(batch: TicketBatch): string {
  const lines: string[] = [
    `# 🎫 Ticket Batch (${batch.provider})`,
    "",
    `**Total Tickets:** ${batch.summary.totalTickets}`,
    `**Estimated Hours:** ${batch.summary.totalEstimatedHours}`,
    `**Types:** ${Object.entries(batch.summary.byType)
      .map(([k, v]) => `${k}: ${v}`)
      .join(", ")}`,
    "",
  ];

  for (const phase of batch.summary.phases) {
    lines.push(`## ${phase}`, "");
  }

  for (const ticket of batch.tickets) {
    lines.push(`### ${ticket.payload.title}`);
    lines.push("");
    lines.push(ticket.payload.body.slice(0, 500));
    if (ticket.payload.body.length > 500) lines.push("...");
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  return lines.join("\n");
}
