import { describe, expect, it } from "vitest";
import {
  generateInnovationBranchName,
  generateInnovationProposal,
  generateInnovationProposalFileName,
} from "../innovation-proposal.js";

function idea(index: number, implementationHint = `Hint ${index}`) {
  return {
    title: `Idea ${index}`,
    description: `Description ${index}`,
    potentialImpact: `Impact ${index}`,
    implementationHint,
  };
}

describe("innovation proposal generation", () => {
  it("generates the current title, body, filename, and top-five formatting", () => {
    const proposal = generateInnovationProposal([
      idea(1),
      idea(2, ""),
      idea(3),
      idea(4),
      idea(5),
      idea(6),
    ]);

    expect(proposal.title).toBe("💡 Innovation Ideas: Idea 1");
    expect(proposal.body).toBe(
      [
        "## 💡 Innovation Proposal",
        "",
        "Generated by **Innovator AI** — ideas from multiple creativity frameworks.",
        "",
        "### Top Ideas",
        "",
        "#### 1. Idea 1",
        "",
        "Description 1",
        "",
        "**Potential Impact:** Impact 1",
        "**Implementation:** Hint 1",
        "",
        "#### 2. Idea 2",
        "",
        "Description 2",
        "",
        "**Potential Impact:** Impact 2",
        "",
        "",
        "#### 3. Idea 3",
        "",
        "Description 3",
        "",
        "**Potential Impact:** Impact 3",
        "**Implementation:** Hint 3",
        "",
        "#### 4. Idea 4",
        "",
        "Description 4",
        "",
        "**Potential Impact:** Impact 4",
        "**Implementation:** Hint 4",
        "",
        "#### 5. Idea 5",
        "",
        "Description 5",
        "",
        "**Potential Impact:** Impact 5",
        "**Implementation:** Hint 5",
        "",
        "---",
        "*Generated by [Innovator](https://github.com/josedab/innovator)*",
      ].join("\n")
    );
    expect(proposal.body).not.toContain("Idea 6");
  });

  it("generates the current filename from its timestamp", () => {
    expect(generateInnovationProposalFileName(1700000000000)).toBe("innovation-1700000000000.md");
  });

  it("generates the current branch name from its independent timestamp", () => {
    expect(generateInnovationBranchName(1700000000999)).toBe("innovation/1700000000999");
  });
});
