import { z } from "zod";

// ---- Known Models ----

/** Advisory list of known models. Unknown models produce a warning, not a hard error. */
export const KNOWN_MODELS = [
  "gpt-4.1",
  "gpt-4.1-mini",
  "gpt-5",
  "gpt-5-mini",
  "claude-sonnet-4.5",
  "claude-sonnet-4",
  ...(process.env.INNOVATOR_EXTRA_MODELS ?? "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean),
] as string[];

/** A model identifier string. Any string is accepted; unknown models produce a warning, not an error. */
export type KnownModel = string;

// ---- Concurrency ----

/** Maximum number of concurrent LLM requests for batch angle generation. */
export const MAX_CONCURRENCY = 2;

// ---- Angles ----

/** All recognized innovation angle identifiers as a readonly tuple. */
export const ANGLE_IDS = [
  "scamper",
  "first-principles",
  "cross-domain",
  "constraints",
  "inversion",
  "perspectives",
  "what-if",
  "trend-collision",
] as const;

/** Union type of valid innovation angle identifiers. */
export type AngleId = (typeof ANGLE_IDS)[number];

/** Metadata for a single innovation angle. */
export interface AngleDefinition {
  id: AngleId;
  name: string;
  shortDescription: string;
  icon: string;
}

// ---- Investigation ----

/** Zod schema for validating investigation results returned by the LLM. */
export const InvestigationSchema = z.object({
  summary: z.string().max(5000).describe("A concise summary of the subject"),
  keyAspects: z
    .array(
      z.object({
        title: z.string().max(500),
        description: z.string().max(2000),
      })
    )
    .max(20)
    .describe("Key aspects or components of the subject"),
  currentState: z.string().max(5000).describe("Current state of the art or practice"),
  challenges: z.array(z.string().max(2000)).max(20).describe("Main challenges or pain points"),
  opportunities: z.array(z.string().max(2000)).max(20).describe("Potential opportunity areas"),
});

/** Structured investigation result containing summary, aspects, state, challenges, and opportunities. */
export type Investigation = z.infer<typeof InvestigationSchema>;

// ---- Innovation ----

/** Zod schema for a single innovation idea generated by an angle. */
export const InnovationIdeaSchema = z.object({
  title: z.string().max(500),
  description: z.string().max(5000),
  potentialImpact: z.string().max(2000),
  implementationHint: z.string().max(2000),
});

/** Zod schema for the result of applying a single innovation angle. */
export const AngleResultSchema = z.object({
  angleId: z.string().max(100),
  angleName: z.string().max(200),
  ideas: z.array(InnovationIdeaSchema).max(50),
  reasoning: z.string().max(5000).describe("How this angle was applied"),
});

/** A single innovation idea with title, description, impact, and implementation hint. */
export type InnovationIdea = z.infer<typeof InnovationIdeaSchema>;

/** Result of applying one innovation angle, containing ideas and reasoning. */
export type AngleResult = z.infer<typeof AngleResultSchema>;

// ---- Auto-Mode Pipeline ----

/** Zod schema for the synthesis of results across all innovation angles. */
export const SynthesisSchema = z.object({
  topIdeas: z
    .array(
      z.object({
        title: z.string().max(500),
        description: z.string().max(5000),
        sourceAngle: z.string().max(200),
        potentialImpact: z.string().max(2000),
        feasibility: z.enum(["low", "medium", "high"]),
      })
    )
    .max(50),
  themes: z.array(z.string().max(500)).max(30).describe("Cross-cutting themes found"),
  recommendation: z.string().max(5000).describe("Overall strategic recommendation"),
});

/** Synthesized output ranking top ideas, identifying themes, and providing a recommendation. */
export type Synthesis = z.infer<typeof SynthesisSchema>;

/** The current stage of the auto-mode innovation pipeline. */
export type PipelineStage = "investigating" | "generating" | "synthesizing" | "complete" | "error";

/** Progress snapshot emitted during the auto-mode pipeline for each stage transition. */
export interface PipelineProgress {
  stage: PipelineStage;
  currentAngle?: string;
  completedAngles: string[];
  totalAngles: number;
  investigation?: Investigation;
  angleResults: AngleResult[];
  failedAngles?: { angleId: string; error: string }[];
  synthesis?: Synthesis;
  error?: string;
  /** Partial idea being streamed in real-time (before full angle result is available). */
  partialIdea?: {
    angleId: string;
    angleName: string;
    ideaIndex: number;
    content: string;
    complete: boolean;
  };
  /** Whether the pipeline was stopped early by the user. */
  stoppedEarly?: boolean;
}

// ---- Custom Angles ----

/** A custom innovation angle defined by the user with a prompt template. */
export interface CustomAngle {
  id: string;
  name: string;
  description: string;
  /** Prompt template with {{subject}} and {{investigation}} placeholders. */
  promptTemplate: string;
  icon?: string;
  author?: string;
  version?: string;
  tags?: string[];
}

/** Zod schema for validating custom angle definitions. */
export const CustomAngleSchema = z.object({
  id: z
    .string()
    .min(1)
    .max(100)
    .regex(/^[a-z0-9-]+$/, "ID must be lowercase alphanumeric with hyphens"),
  name: z.string().min(1).max(200),
  description: z.string().min(1).max(2000),
  promptTemplate: z.string().min(1).max(10000),
  icon: z.string().max(10).optional(),
  author: z.string().max(200).optional(),
  version: z.string().max(50).optional(),
  tags: z.array(z.string().max(100)).max(20).optional(),
});

/** Schema for an angle pack file (.angle.json). */
export const AnglePackSchema = z.object({
  name: z.string().min(1).max(200),
  description: z.string().max(2000).optional(),
  version: z.string().max(50).optional(),
  angles: z.array(CustomAngleSchema).min(1).max(50),
});

/** An angle pack containing one or more custom angles for import/export. */
export type AnglePack = z.infer<typeof AnglePackSchema>;

// ---- Request / Response ----

/** Request payload for the investigate API endpoint. */
export interface InvestigateRequest {
  subject: string;
  model?: string;
}

/** Request payload for the innovate API endpoint. */
export interface InnovateRequest {
  subject: string;
  investigation: Investigation;
  angles: AngleId[];
  model?: string;
}

/** Request payload for the auto-mode API endpoint. */
export interface AutoRequest {
  subject: string;
  model?: string;
}

// ---- Plugin System ----

/** Base interface all plugins must implement. */
export interface PluginBase {
  id: string;
  name: string;
  version: string;
  description?: string;
}

/** A plugin that provides custom innovation angles. */
export interface AnglePlugin extends PluginBase {
  type: "angle";
  angles: CustomAngle[];
}

/** Export format configuration. */
export interface ExportFormat {
  id: string;
  name: string;
  extension: string;
}

/** A plugin that provides export capabilities. */
export interface ExporterPlugin extends PluginBase {
  type: "exporter";
  formats: ExportFormat[];
  export(data: ExportData, format: string): Promise<string | Buffer>;
}

/** Data passed to exporter plugins. */
export interface ExportData {
  subject: string;
  investigation?: Investigation;
  angleResults: AngleResult[];
  synthesis?: Synthesis;
  metadata?: Record<string, unknown>;
}

/** A plugin that provides visualization capabilities. */
export interface VisualizerPlugin extends PluginBase {
  type: "visualizer";
  render(data: ExportData): Promise<string>;
}

/** Union of all plugin types. */
export type InnovatorPlugin = AnglePlugin | ExporterPlugin | VisualizerPlugin;

/** Plugin manifest for discovery and loading. */
export interface PluginManifest {
  id: string;
  name: string;
  version: string;
  type: "angle" | "exporter" | "visualizer";
  description?: string;
  main: string;
}

// ---- API Types ----

/** API key metadata for programmatic access. */
export interface ApiKeyInfo {
  id: string;
  name: string;
  prefix: string;
  createdAt: string;
  lastUsedAt?: string;
}

/** Rate limit information returned in API responses. */
export interface RateLimitInfo {
  limit: number;
  remaining: number;
  resetAt: string;
}

// ---- Presets & Templates ----

/** A domain preset with pre-selected angles and customized prompts. */
export interface Preset {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: string;
  suggestedSubject: string;
  selectedAngles: AngleId[];
  /** Optional custom prompt hints injected into investigation. */
  contextHints?: string;
  tags?: string[];
}

// ---- History & Persistence ----

/** A stored innovation session with all pipeline results. */
export interface SessionRecord {
  id: string;
  subject: string;
  createdAt: string;
  updatedAt: string;
  investigation?: Investigation;
  angleResults: AngleResult[];
  synthesis?: Synthesis;
  tags: string[];
  notes?: string;
  presetId?: string;
}

/** Search/filter options for querying session history. */
export interface HistoryQuery {
  search?: string;
  tags?: string[];
  fromDate?: string;
  toDate?: string;
  angleId?: string;
  limit?: number;
  offset?: number;
}

// ---- Multi-Model Orchestration ----

/** Pipeline stage that can have a model assigned. */
export type PipelineModelStage = "investigation" | "generation" | "synthesis";

/** Model capability metadata for smart routing. */
export interface ModelCapability {
  modelId: string;
  displayName: string;
  strengths: PipelineModelStage[];
  costTier: "low" | "medium" | "high";
  speedTier: "fast" | "medium" | "slow";
  qualityTier: "standard" | "high" | "premium";
}

/** Per-stage model configuration for the pipeline. */
export interface ModelRouting {
  investigation?: string;
  generation?: string;
  synthesis?: string;
}

/** Result of comparing the same angle across multiple models. */
export interface ModelComparisonResult {
  angleId: string;
  results: Array<{
    model: string;
    angleResult: AngleResult;
    durationMs: number;
  }>;
}

// ---- Collaborative Sessions ----

/** A collaborative ideation session. */
export interface CollaborativeSession {
  id: string;
  roomCode: string;
  subject: string;
  hostUserId: string;
  createdAt: string;
  status: "waiting" | "active" | "completed";
  participants: SessionParticipant[];
  angleAssignments: Record<string, AngleId[]>;
  ideas: CollaborativeIdea[];
  votes: Record<string, string[]>;
}

/** A participant in a collaborative session. */
export interface SessionParticipant {
  userId: string;
  displayName: string;
  joinedAt: string;
  isHost: boolean;
  assignedAngles: AngleId[];
  status: "connected" | "disconnected";
}

/** An idea submitted in a collaborative session. */
export interface CollaborativeIdea {
  id: string;
  authorId: string;
  angleId: string;
  title: string;
  description: string;
  potentialImpact: string;
  votes: number;
  comments: IdeaComment[];
  createdAt: string;
}

/** A comment on a collaborative idea. */
export interface IdeaComment {
  id: string;
  authorId: string;
  authorName: string;
  content: string;
  createdAt: string;
}

/** Events emitted by the collaborative session system. */
export type CollaborativeEvent =
  | { type: "participant_joined"; participant: SessionParticipant }
  | { type: "participant_left"; userId: string }
  | { type: "idea_submitted"; idea: CollaborativeIdea }
  | { type: "idea_voted"; ideaId: string; userId: string; votes: number }
  | { type: "comment_added"; ideaId: string; comment: IdeaComment }
  | { type: "angle_assigned"; userId: string; angles: AngleId[] }
  | { type: "session_started"; subject: string }
  | { type: "session_completed" }
  | { type: "ideas_merged"; sourceIds: string[]; mergedIdea: CollaborativeIdea };
