import { z } from "zod";

// ---- Known Models ----

/** Advisory list of known models. Unknown models produce a warning, not a hard error. */
export const KNOWN_MODELS = [
  "gpt-4.1",
  "gpt-4.1-mini",
  "gpt-5",
  "gpt-5-mini",
  "claude-sonnet-4.5",
  "claude-sonnet-4",
  ...(process.env.INNOVATOR_EXTRA_MODELS ?? "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean),
] as string[];

/** A model identifier string. Any string is accepted; unknown models produce a warning, not an error. */
export type KnownModel = string;

// ---- Concurrency ----

/** Maximum number of concurrent LLM requests for batch angle generation. */
export const MAX_CONCURRENCY = 2;

// ---- Angles ----

/** All recognized innovation angle identifiers as a readonly tuple. */
export const ANGLE_IDS = [
  "scamper",
  "first-principles",
  "cross-domain",
  "constraints",
  "inversion",
  "perspectives",
  "what-if",
  "trend-collision",
] as const;

/** Union type of valid innovation angle identifiers. */
export type AngleId = (typeof ANGLE_IDS)[number];

/** Metadata for a single innovation angle. */
export interface AngleDefinition {
  /** Unique identifier for this angle (e.g., `"scamper"`, `"first-principles"`). */
  id: AngleId;
  /** Human-readable display name. */
  name: string;
  /** Brief description of the angle's approach. */
  shortDescription: string;
  /** Emoji icon for UI display. */
  icon: string;
}

// ---- Investigation ----

/** Zod schema for validating investigation results returned by the LLM. */
export const InvestigationSchema = z.object({
  summary: z.string().max(5000).describe("A concise summary of the subject"),
  keyAspects: z
    .array(
      z.object({
        title: z.string().max(500),
        description: z.string().max(2000),
      })
    )
    .max(20)
    .describe("Key aspects or components of the subject"),
  currentState: z.string().max(5000).describe("Current state of the art or practice"),
  challenges: z.array(z.string().max(2000)).max(20).describe("Main challenges or pain points"),
  opportunities: z.array(z.string().max(2000)).max(20).describe("Potential opportunity areas"),
});

/** Structured investigation result containing summary, aspects, state, challenges, and opportunities. */
export type Investigation = z.infer<typeof InvestigationSchema>;

// ---- Innovation ----

/** Zod schema for a single innovation idea generated by an angle. */
export const InnovationIdeaSchema = z.object({
  title: z.string().max(500),
  description: z.string().max(5000),
  potentialImpact: z.string().max(2000),
  implementationHint: z.string().max(2000),
});

/** Zod schema for the result of applying a single innovation angle. */
export const AngleResultSchema = z.object({
  angleId: z.string().max(100),
  angleName: z.string().max(200),
  ideas: z.array(InnovationIdeaSchema).max(50),
  reasoning: z.string().max(5000).describe("How this angle was applied"),
});

/** A single innovation idea with title, description, impact, and implementation hint. */
export type InnovationIdea = z.infer<typeof InnovationIdeaSchema>;

/** Result of applying one innovation angle, containing ideas and reasoning. */
export type AngleResult = z.infer<typeof AngleResultSchema>;

// ---- Auto-Mode Pipeline ----

/** Zod schema for the synthesis of results across all innovation angles. */
export const SynthesisSchema = z.object({
  topIdeas: z
    .array(
      z.object({
        title: z.string().max(500),
        description: z.string().max(5000),
        sourceAngle: z.string().max(200),
        potentialImpact: z.string().max(2000),
        feasibility: z.enum(["low", "medium", "high"]),
      })
    )
    .max(50),
  themes: z.array(z.string().max(500)).max(30).describe("Cross-cutting themes found"),
  recommendation: z.string().max(5000).describe("Overall strategic recommendation"),
});

/** Synthesized output ranking top ideas, identifying themes, and providing a recommendation. */
export type Synthesis = z.infer<typeof SynthesisSchema>;

/** The current stage of the auto-mode innovation pipeline. */
export type PipelineStage = "investigating" | "generating" | "synthesizing" | "complete" | "error";

/** Progress snapshot emitted during the auto-mode pipeline for each stage transition. */
export interface PipelineProgress {
  /** Current pipeline stage. */
  stage: PipelineStage;
  /** Angle currently being processed (if in "generating" stage). */
  currentAngle?: string;
  /** IDs of angles that have finished generating. */
  completedAngles: string[];
  /** Total number of angles to process. */
  totalAngles: number;
  /** Investigation result (available after "investigating" completes). */
  investigation?: Investigation;
  /** Accumulated angle results as each angle completes. */
  angleResults: AngleResult[];
  /** Angles that failed during generation. */
  failedAngles?: { angleId: string; error: string }[];
  /** Final synthesis (available after "synthesizing" completes). */
  synthesis?: Synthesis;
  /** Error message if stage is "error". */
  error?: string;
  /** Partial idea being streamed in real-time (before full angle result is available). */
  partialIdea?: {
    angleId: string;
    angleName: string;
    ideaIndex: number;
    content: string;
    complete: boolean;
  };
  /** Whether the pipeline was stopped early by the user. */
  stoppedEarly?: boolean;
}

// ---- Custom Angles ----

/** A custom innovation angle defined by the user with a prompt template. */
export interface CustomAngle {
  /** Unique identifier (lowercase alphanumeric with hyphens). */
  id: string;
  /** Human-readable display name. */
  name: string;
  /** Brief description of the angle's approach. */
  description: string;
  /** Prompt template with {{subject}} and {{investigation}} placeholders. */
  promptTemplate: string;
  /** Emoji icon for UI display. */
  icon?: string;
  /** Author of the custom angle. */
  author?: string;
  /** Semver version string. */
  version?: string;
  /** Categorization tags for discovery and filtering. */
  tags?: string[];
}

/** Zod schema for validating custom angle definitions. */
export const CustomAngleSchema = z.object({
  id: z
    .string()
    .min(1)
    .max(100)
    .regex(/^[a-z0-9-]+$/, "ID must be lowercase alphanumeric with hyphens"),
  name: z.string().min(1).max(200),
  description: z.string().min(1).max(2000),
  promptTemplate: z.string().min(1).max(10000),
  icon: z.string().max(10).optional(),
  author: z.string().max(200).optional(),
  version: z.string().max(50).optional(),
  tags: z.array(z.string().max(100)).max(20).optional(),
});

/** Schema for an angle pack file (.angle.json). */
export const AnglePackSchema = z.object({
  name: z.string().min(1).max(200),
  description: z.string().max(2000).optional(),
  version: z.string().max(50).optional(),
  angles: z.array(CustomAngleSchema).min(1).max(50),
});

/** An angle pack containing one or more custom angles for import/export. */
export type AnglePack = z.infer<typeof AnglePackSchema>;

// ---- Request / Response ----

/** Request payload for the investigate API endpoint. */
export interface InvestigateRequest {
  subject: string;
  model?: string;
}

/** Request payload for the innovate API endpoint. */
export interface InnovateRequest {
  subject: string;
  investigation: Investigation;
  angles: AngleId[];
  model?: string;
}

/** Request payload for the auto-mode API endpoint. */
export interface AutoRequest {
  subject: string;
  model?: string;
}

// ---- Plugin System ----

/** Base interface all plugins must implement. */
export interface PluginBase {
  /** Unique plugin identifier (used for registry lookups). */
  id: string;
  /** Human-readable plugin name. */
  name: string;
  /** Semver version string. */
  version: string;
  /** Optional description shown in plugin listings. */
  description?: string;
}

/** A plugin that provides custom innovation angles. */
export interface AnglePlugin extends PluginBase {
  type: "angle";
  angles: CustomAngle[];
}

/** Export format configuration. */
export interface ExportFormat {
  /** Format identifier (e.g., `"markdown"`, `"json"`). */
  id: string;
  /** Human-readable format name. */
  name: string;
  /** File extension including the dot (e.g., `".md"`). */
  extension: string;
}

/** A plugin that provides export capabilities. */
export interface ExporterPlugin extends PluginBase {
  type: "exporter";
  formats: ExportFormat[];
  export(data: ExportData, format: string): Promise<string | Buffer>;
}

/** Data passed to exporter plugins. */
export interface ExportData {
  /** The innovation subject being exported. */
  subject: string;
  /** Investigation results (if available). */
  investigation?: Investigation;
  /** Per-angle idea results. */
  angleResults: AngleResult[];
  /** Synthesized top ideas and recommendation. */
  synthesis?: Synthesis;
  /** Arbitrary metadata attached by the caller. */
  metadata?: Record<string, unknown>;
}

/** A plugin that provides visualization capabilities. */
export interface VisualizerPlugin extends PluginBase {
  type: "visualizer";
  render(data: ExportData): Promise<string>;
}

/** Union of all plugin types. */
export type InnovatorPlugin = AnglePlugin | ExporterPlugin | VisualizerPlugin;

/** Plugin manifest for discovery and loading. */
export interface PluginManifest {
  /** Unique plugin identifier. */
  id: string;
  /** Human-readable plugin name. */
  name: string;
  /** Semver version string. */
  version: string;
  /** Plugin category determining available capabilities. */
  type: "angle" | "exporter" | "visualizer";
  /** Optional description shown in plugin listings. */
  description?: string;
  /** Entry point file path or npm package name. */
  main: string;
}

// ---- API Types ----

/** API key metadata for programmatic access. */
export interface ApiKeyInfo {
  /** Unique key identifier. */
  id: string;
  /** Human-readable label for the key. */
  name: string;
  /** First characters of the key for identification (e.g., `"sk-abc..."`). */
  prefix: string;
  /** ISO 8601 timestamp when the key was created. */
  createdAt: string;
  /** ISO 8601 timestamp of the last API call using this key. */
  lastUsedAt?: string;
}

/** Rate limit information returned in API responses. */
export interface RateLimitInfo {
  /** Maximum requests allowed in the current window. */
  limit: number;
  /** Remaining requests in the current window. */
  remaining: number;
  /** ISO 8601 timestamp when the rate limit window resets. */
  resetAt: string;
}

// ---- Presets & Templates ----

/** A domain preset with pre-selected angles and customized prompts. */
export interface Preset {
  /** Unique preset identifier. */
  id: string;
  /** Human-readable preset name. */
  name: string;
  /** Description of what this preset is optimized for. */
  description: string;
  /** Emoji icon for UI display. */
  icon: string;
  /** Grouping category (e.g., `"product"`, `"sustainability"`). */
  category: string;
  /** Example subject to help users understand the preset's scope. */
  suggestedSubject: string;
  /** Pre-selected angles activated by this preset. */
  selectedAngles: AngleId[];
  /** Optional custom prompt hints injected into investigation. */
  contextHints?: string;
  /** Categorization tags for filtering. */
  tags?: string[];
}

// ---- History & Persistence ----

/** A stored innovation session with all pipeline results. */
export interface SessionRecord {
  /** Unique session identifier. */
  id: string;
  /** The innovation subject. */
  subject: string;
  /** ISO 8601 timestamp when the session was created. */
  createdAt: string;
  /** ISO 8601 timestamp when the session was last modified. */
  updatedAt: string;
  /** Investigation results (if pipeline reached this stage). */
  investigation?: Investigation;
  /** Per-angle idea results. */
  angleResults: AngleResult[];
  /** Synthesized top ideas and recommendation. */
  synthesis?: Synthesis;
  /** User-defined tags for categorization. */
  tags: string[];
  /** Free-form user notes attached to the session. */
  notes?: string;
  /** Preset used to run this session (if any). */
  presetId?: string;
}

/** Search/filter options for querying session history. */
export interface HistoryQuery {
  /** Full-text search across subject and idea content. */
  search?: string;
  /** Filter to sessions containing all specified tags. */
  tags?: string[];
  /** ISO 8601 lower bound for creation date. */
  fromDate?: string;
  /** ISO 8601 upper bound for creation date. */
  toDate?: string;
  /** Filter to sessions that used a specific angle. */
  angleId?: string;
  /** Maximum number of results to return. */
  limit?: number;
  /** Number of results to skip (for pagination). */
  offset?: number;
}

// ---- Multi-Model Orchestration ----

/** Pipeline stage that can have a model assigned. */
export type PipelineModelStage = "investigation" | "generation" | "synthesis";

/** Model capability metadata for smart routing. */
export interface ModelCapability {
  /** LLM model identifier string. */
  modelId: string;
  /** Human-readable model name. */
  displayName: string;
  /** Pipeline stages this model excels at. */
  strengths: PipelineModelStage[];
  /** Relative cost tier for budget-aware routing. */
  costTier: "low" | "medium" | "high";
  /** Relative speed tier for latency-aware routing. */
  speedTier: "fast" | "medium" | "slow";
  /** Relative quality tier for output fidelity. */
  qualityTier: "standard" | "high" | "premium";
}

/** Per-stage model configuration for the pipeline. */
export interface ModelRouting {
  /** Model to use for the investigation stage. */
  investigation?: string;
  /** Model to use for the idea generation stage. */
  generation?: string;
  /** Model to use for the synthesis stage. */
  synthesis?: string;
}

/** Result of comparing the same angle across multiple models. */
export interface ModelComparisonResult {
  /** The angle that was compared. */
  angleId: string;
  /** Per-model results with timing data. */
  results: Array<{
    /** Model identifier used for this run. */
    model: string;
    /** The angle result produced by this model. */
    angleResult: AngleResult;
    /** Wall-clock duration in milliseconds. */
    durationMs: number;
  }>;
}

// ---- Collaborative Sessions ----

/** A collaborative ideation session. */
export interface CollaborativeSession {
  /** Unique session identifier. */
  id: string;
  /** Short join code participants use to enter the session. */
  roomCode: string;
  /** The innovation subject being brainstormed. */
  subject: string;
  /** User ID of the session host. */
  hostUserId: string;
  /** ISO 8601 timestamp when the session was created. */
  createdAt: string;
  /** Current session lifecycle state. */
  status: "waiting" | "active" | "completed";
  /** All participants including the host. */
  participants: SessionParticipant[];
  /** Map of userId → assigned angle IDs. */
  angleAssignments: Record<string, AngleId[]>;
  /** Ideas submitted during the session. */
  ideas: CollaborativeIdea[];
  /** Map of ideaId → array of voter userIds. */
  votes: Record<string, string[]>;
}

/** A participant in a collaborative session. */
export interface SessionParticipant {
  userId: string;
  displayName: string;
  joinedAt: string;
  isHost: boolean;
  assignedAngles: AngleId[];
  status: "connected" | "disconnected";
}

/** An idea submitted in a collaborative session. */
export interface CollaborativeIdea {
  id: string;
  authorId: string;
  angleId: string;
  title: string;
  description: string;
  potentialImpact: string;
  votes: number;
  comments: IdeaComment[];
  createdAt: string;
}

/** A comment on a collaborative idea. */
export interface IdeaComment {
  id: string;
  authorId: string;
  authorName: string;
  content: string;
  createdAt: string;
}

/** Events emitted by the collaborative session system. */
export type CollaborativeEvent =
  | { type: "participant_joined"; participant: SessionParticipant }
  | { type: "participant_left"; userId: string }
  | { type: "idea_submitted"; idea: CollaborativeIdea }
  | { type: "idea_voted"; ideaId: string; userId: string; votes: number }
  | { type: "comment_added"; ideaId: string; comment: IdeaComment }
  | { type: "angle_assigned"; userId: string; angles: AngleId[] }
  | { type: "session_started"; subject: string }
  | { type: "session_completed" }
  | { type: "ideas_merged"; sourceIds: string[]; mergedIdea: CollaborativeIdea };
