import { z } from "zod";

// ---- Known Models ----

/** Advisory list of known models. Unknown models produce a warning, not a hard error. */
export const KNOWN_MODELS = [
  "gpt-4.1",
  "gpt-4.1-mini",
  "gpt-5",
  "gpt-5-mini",
  "claude-sonnet-4.5",
  "claude-sonnet-4",
  ...(process.env.INNOVATOR_EXTRA_MODELS ?? "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean),
] as string[];

/** A model identifier string. Any string is accepted; unknown models produce a warning, not an error. */
export type KnownModel = string;

// ---- Concurrency ----

/** Maximum number of concurrent LLM requests for batch angle generation. */
export const MAX_CONCURRENCY = 2;

// ---- Angles ----

/** All recognized innovation angle identifiers as a readonly tuple. */
export const ANGLE_IDS = [
  "scamper",
  "first-principles",
  "cross-domain",
  "constraints",
  "inversion",
  "perspectives",
  "what-if",
  "trend-collision",
] as const;

/** Union type of valid innovation angle identifiers. */
export type AngleId = (typeof ANGLE_IDS)[number];

/** Metadata for a single innovation angle. */
export interface AngleDefinition {
  id: AngleId;
  name: string;
  shortDescription: string;
  icon: string;
}

// ---- Investigation ----

/** Zod schema for validating investigation results returned by the LLM. */
export const InvestigationSchema = z.object({
  summary: z.string().max(5000).describe("A concise summary of the subject"),
  keyAspects: z
    .array(
      z.object({
        title: z.string().max(500),
        description: z.string().max(2000),
      })
    )
    .max(20)
    .describe("Key aspects or components of the subject"),
  currentState: z.string().max(5000).describe("Current state of the art or practice"),
  challenges: z.array(z.string().max(2000)).max(20).describe("Main challenges or pain points"),
  opportunities: z.array(z.string().max(2000)).max(20).describe("Potential opportunity areas"),
});

/** Structured investigation result containing summary, aspects, state, challenges, and opportunities. */
export type Investigation = z.infer<typeof InvestigationSchema>;

// ---- Innovation ----

/** Zod schema for a single innovation idea generated by an angle. */
export const InnovationIdeaSchema = z.object({
  title: z.string().max(500),
  description: z.string().max(5000),
  potentialImpact: z.string().max(2000),
  implementationHint: z.string().max(2000),
});

/** Zod schema for the result of applying a single innovation angle. */
export const AngleResultSchema = z.object({
  angleId: z.string().max(100),
  angleName: z.string().max(200),
  ideas: z.array(InnovationIdeaSchema).max(50),
  reasoning: z.string().max(5000).describe("How this angle was applied"),
});

/** A single innovation idea with title, description, impact, and implementation hint. */
export type InnovationIdea = z.infer<typeof InnovationIdeaSchema>;

/** Result of applying one innovation angle, containing ideas and reasoning. */
export type AngleResult = z.infer<typeof AngleResultSchema>;

// ---- Auto-Mode Pipeline ----

/** Zod schema for the synthesis of results across all innovation angles. */
export const SynthesisSchema = z.object({
  topIdeas: z
    .array(
      z.object({
        title: z.string().max(500),
        description: z.string().max(5000),
        sourceAngle: z.string().max(200),
        potentialImpact: z.string().max(2000),
        feasibility: z.enum(["low", "medium", "high"]),
      })
    )
    .max(50),
  themes: z.array(z.string().max(500)).max(30).describe("Cross-cutting themes found"),
  recommendation: z.string().max(5000).describe("Overall strategic recommendation"),
});

/** Synthesized output ranking top ideas, identifying themes, and providing a recommendation. */
export type Synthesis = z.infer<typeof SynthesisSchema>;

/** The current stage of the auto-mode innovation pipeline. */
export type PipelineStage = "investigating" | "generating" | "synthesizing" | "complete" | "error";

/** Progress snapshot emitted during the auto-mode pipeline for each stage transition. */
export interface PipelineProgress {
  stage: PipelineStage;
  currentAngle?: string;
  completedAngles: string[];
  totalAngles: number;
  investigation?: Investigation;
  angleResults: AngleResult[];
  failedAngles?: { angleId: string; error: string }[];
  synthesis?: Synthesis;
  error?: string;
}

// ---- Request / Response ----

/** Request payload for the investigate API endpoint. */
export interface InvestigateRequest {
  subject: string;
  model?: string;
}

/** Request payload for the innovate API endpoint. */
export interface InnovateRequest {
  subject: string;
  investigation: Investigation;
  angles: AngleId[];
  model?: string;
}

/** Request payload for the auto-mode API endpoint. */
export interface AutoRequest {
  subject: string;
  model?: string;
}
