/**
 * @module export
 *
 * Export innovation results to various formats.
 * Supports Markdown, JSON, and GitHub Issues via adapter pattern.
 */

import type { ExportData } from "../types.js";

/** Export result containing the formatted output and metadata. */
export interface ExportResult {
  content: string;
  mimeType: string;
  extension: string;
  filename: string;
}

/** Adapter interface for third-party integrations. */
export interface IntegrationAdapter {
  id: string;
  name: string;
  export(data: ExportData, options?: Record<string, unknown>): Promise<{ url?: string; id?: string }>;
}

// ---- Built-in Exporters ----

/** Export to Markdown format. */
export function exportToMarkdown(data: ExportData): ExportResult {
  const lines: string[] = [];
  const subject = data.subject;

  lines.push(`# Innovation Report: ${subject}`);
  lines.push("");
  lines.push(`*Generated on ${new Date().toISOString().split("T")[0]}*`);
  lines.push("");

  if (data.investigation) {
    lines.push("## Investigation");
    lines.push("");
    lines.push(`### Summary`);
    lines.push(data.investigation.summary);
    lines.push("");

    lines.push("### Key Aspects");
    for (const aspect of data.investigation.keyAspects) {
      lines.push(`- **${aspect.title}**: ${aspect.description}`);
    }
    lines.push("");

    lines.push("### Current State");
    lines.push(data.investigation.currentState);
    lines.push("");

    lines.push("### Challenges");
    for (const c of data.investigation.challenges) {
      lines.push(`- ${c}`);
    }
    lines.push("");

    lines.push("### Opportunities");
    for (const o of data.investigation.opportunities) {
      lines.push(`- ${o}`);
    }
    lines.push("");
  }

  if (data.angleResults.length > 0) {
    lines.push("## Innovation Ideas by Angle");
    lines.push("");

    for (const angle of data.angleResults) {
      lines.push(`### ${angle.angleName}`);
      lines.push("");
      lines.push(`*${angle.reasoning}*`);
      lines.push("");

      for (const idea of angle.ideas) {
        lines.push(`#### ${idea.title}`);
        lines.push("");
        lines.push(idea.description);
        lines.push("");
        lines.push(`- **Impact**: ${idea.potentialImpact}`);
        lines.push(`- **How to start**: ${idea.implementationHint}`);
        lines.push("");
      }
    }
  }

  if (data.synthesis) {
    lines.push("## Synthesis");
    lines.push("");

    lines.push("### Top Ideas");
    lines.push("");
    for (const idea of data.synthesis.topIdeas) {
      lines.push(`#### ${idea.title} (${idea.feasibility} feasibility)`);
      lines.push("");
      lines.push(idea.description);
      lines.push(`- **Source**: ${idea.sourceAngle}`);
      lines.push(`- **Impact**: ${idea.potentialImpact}`);
      lines.push("");
    }

    lines.push("### Themes");
    for (const theme of data.synthesis.themes) {
      lines.push(`- ${theme}`);
    }
    lines.push("");

    lines.push("### Recommendation");
    lines.push(data.synthesis.recommendation);
    lines.push("");
  }

  const slug = subject.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 50);

  return {
    content: lines.join("\n"),
    mimeType: "text/markdown",
    extension: ".md",
    filename: `innovation-${slug}.md`,
  };
}

/** Export to JSON format. */
export function exportToJson(data: ExportData): ExportResult {
  const slug = data.subject.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 50);
  return {
    content: JSON.stringify(data, null, 2),
    mimeType: "application/json",
    extension: ".json",
    filename: `innovation-${slug}.json`,
  };
}

/** Generate a GitHub Issue body from innovation data. */
export function generateGitHubIssueBody(data: ExportData): { title: string; body: string; labels: string[] } {
  const title = `💡 Innovation: ${data.subject}`;
  const lines: string[] = [];

  lines.push(`## Innovation Ideas for: ${data.subject}`);
  lines.push("");

  if (data.synthesis) {
    lines.push("### Top Ideas");
    lines.push("");
    for (const idea of data.synthesis.topIdeas) {
      lines.push(`- [ ] **${idea.title}** (${idea.feasibility} feasibility)`);
      lines.push(`  ${idea.description}`);
      lines.push("");
    }

    lines.push("### Recommendation");
    lines.push(data.synthesis.recommendation);
  } else if (data.angleResults.length > 0) {
    for (const angle of data.angleResults) {
      lines.push(`### ${angle.angleName}`);
      for (const idea of angle.ideas) {
        lines.push(`- [ ] **${idea.title}**: ${idea.description}`);
      }
      lines.push("");
    }
  }

  lines.push("");
  lines.push("---");
  lines.push("*Generated by [Innovator](https://github.com/innovator)*");

  return {
    title,
    body: lines.join("\n"),
    labels: ["innovation", "ideas"],
  };
}

/** Export data for clipboard (plain text summary). */
export function exportToClipboard(data: ExportData): string {
  const lines: string[] = [];
  lines.push(`Innovation Report: ${data.subject}`);
  lines.push("=".repeat(40));

  if (data.synthesis) {
    lines.push("\nTop Ideas:");
    for (const idea of data.synthesis.topIdeas) {
      lines.push(`\n• ${idea.title} [${idea.feasibility}]`);
      lines.push(`  ${idea.description}`);
    }
    lines.push(`\nRecommendation: ${data.synthesis.recommendation}`);
  } else {
    for (const angle of data.angleResults) {
      lines.push(`\n${angle.angleName}:`);
      for (const idea of angle.ideas) {
        lines.push(`  • ${idea.title}: ${idea.description}`);
      }
    }
  }

  return lines.join("\n");
}
