import { z } from "zod";
import { generateText, extractJson } from "../copilot/client.js";
import { withRetry } from "../copilot/retry.js";
import type { Investigation, AngleResult, InnovationIdea } from "../types.js";
import {
  ReasoningChainSchema,
  ConfidenceDecompositionSchema,
  CounterfactualSchema,
  type XaiDecisionPoint,
  type ReasoningChain,
  type ConfidenceDecomposition,
  type Counterfactual,
  type ExplainabilityReport,
  type ExplainabilityConfig,
} from "./types.js";

/** Capture decision points from pipeline data for post-hoc analysis. */
export function captureDecisionPoints(
  investigation: Investigation,
  angleResults: AngleResult[]
): XaiDecisionPoint[] {
  const points: XaiDecisionPoint[] = [];
  const now = new Date().toISOString();

  points.push({
    id: "dp-investigation",
    type: "investigation-trigger",
    timestamp: now,
    description: "Initial subject investigation to identify aspects and opportunities",
    inputs: [investigation.summary.slice(0, 500)],
    output: `Found ${investigation.keyAspects.length} aspects, ${investigation.challenges.length} challenges, ${investigation.opportunities.length} opportunities`,
    confidence: 0.8,
    reasoning: "Structured decomposition of the subject domain",
    alternativesConsidered: [],
  });

  for (const result of angleResults) {
    points.push({
      id: `dp-angle-${result.angleId}`,
      type: "angle-selection",
      timestamp: now,
      description: `Applied ${result.angleName} angle to generate ideas`,
      inputs: [result.reasoning.slice(0, 500)],
      output: `Generated ${result.ideas.length} ideas`,
      confidence: 0.7,
      reasoning: result.reasoning,
      alternativesConsidered: [],
    });

    for (const [idx, idea] of result.ideas.entries()) {
      points.push({
        id: `dp-idea-${result.angleId}-${idx}`,
        type: "idea-generation",
        timestamp: now,
        description: `Generated idea: ${idea.title}`,
        inputs: [result.reasoning.slice(0, 300)],
        output: idea.description.slice(0, 500),
        confidence: 0.6,
        reasoning: `From ${result.angleName}: ${idea.implementationHint}`,
        alternativesConsidered: [],
      });
    }
  }

  return points;
}

function buildReasoningPrompt(
  idea: InnovationIdea,
  angleId: string,
  investigation?: Investigation
): string {
  return `Trace the reasoning chain for why this innovation idea was generated.

Idea: "${idea.title}" — ${idea.description}
Generated by angle: ${angleId}
${investigation ? `Investigation context: ${investigation.summary.slice(0, 1000)}` : ""}

Produce a step-by-step reasoning chain showing:
1. What investigation aspects triggered this idea
2. What reasoning patterns were applied
3. What evidence supports each step
4. Confidence at each step

Respond in JSON:
{
  "steps": [
    {
      "stepNumber": 0,
      "action": "what was done",
      "reasoning": "why this step",
      "evidence": ["supporting evidence"],
      "confidence": 0.0-1.0,
      "parentStepNumber": null
    }
  ],
  "overallConfidence": 0.0-1.0,
  "triggerAspects": ["what triggered this"],
  "patternsApplied": ["what patterns were used"]
}`;
}

function buildConfidencePrompt(idea: InnovationIdea): string {
  return `Decompose the confidence score for this innovation idea into its constituent dimensions.

Idea: "${idea.title}" — ${idea.description}
Impact: ${idea.potentialImpact}

Score each dimension 0-1 with weight and evidence:
- Technical feasibility
- Market demand
- Competitive advantage
- Implementation complexity (inverse)
- Timing appropriateness
- Resource requirements

Respond in JSON:
{
  "overallConfidence": 0.0-1.0,
  "dimensions": [
    {
      "dimension": "name",
      "score": 0.0-1.0,
      "weight": 0.0-1.0,
      "evidence": "why this score"
    }
  ]
}`;
}

function buildCounterfactualPrompt(
  idea: InnovationIdea,
  index: number,
  investigation?: Investigation
): string {
  const staticQuestions = [
    "What if the target market was 10x smaller?",
    "What if a major competitor launched this first?",
    "What if the key technology wasn't available?",
    "What if the budget was halved?",
    "What if the timeline was compressed to 3 months?",
    "What if the regulatory environment became hostile to this approach?",
    "What if the primary user persona had opposite priorities?",
    "What if this had to work offline with no cloud dependency?",
  ];

  // Generate context-aware questions from investigation
  const contextQuestions: string[] = [];
  if (investigation) {
    if (investigation.challenges.length > 0) {
      contextQuestions.push(
        `What if the challenge "${investigation.challenges[0]}" was solved by someone else first?`
      );
    }
    if (investigation.opportunities.length > 0) {
      contextQuestions.push(
        `What if the opportunity "${investigation.opportunities[0]}" no longer existed?`
      );
    }
    if (investigation.keyAspects.length > 0) {
      contextQuestions.push(
        `What if "${investigation.keyAspects[0].title}" worked completely differently?`
      );
    }
  }

  const allQuestions = [...contextQuestions, ...staticQuestions];
  const question = allQuestions[index % allQuestions.length];

  return `Generate a counterfactual analysis for this idea:

Idea: "${idea.title}" — ${idea.description}
Impact: ${idea.potentialImpact}

Counterfactual question: "${question}"

Respond in JSON:
{
  "question": "${question}",
  "originalOutcome": "expected outcome without change",
  "alteredCondition": "the specific condition changed",
  "predictedOutcome": "outcome with the change",
  "impactDelta": -1.0 to 1.0 (negative = worse, positive = better),
  "confidence": 0.0-1.0,
  "explanation": "detailed explanation"
}`;
}

/** Generate a full explainability report for an innovation idea. */
export async function explainIdea(
  idea: InnovationIdea,
  angleId: string,
  investigation?: Investigation,
  angleResults?: AngleResult[],
  config: ExplainabilityConfig = {}
): Promise<ExplainabilityReport> {
  const counterfactualCount = config.counterfactualCount ?? 3;
  const ideaId = `idea-${angleId}-${Date.now()}`;

  // Step 1: Trace reasoning chain
  config.onProgress?.({
    stage: "tracing-reasoning",
    completedSteps: 0,
    totalSteps: 3,
  });

  const reasoningChain = await withRetry(
    async () => {
      const raw = await generateText({
        prompt: buildReasoningPrompt(idea, angleId, investigation),
        model: config.model,
        signal: config.signal,
      });
      const parsed = JSON.parse(extractJson(raw));
      return ReasoningChainSchema.parse({
        ideaId,
        ideaTitle: idea.title,
        ...parsed,
      });
    },
    { signal: config.signal }
  );

  // Step 2: Confidence decomposition
  config.onProgress?.({
    stage: "decomposing-confidence",
    completedSteps: 1,
    totalSteps: 3,
  });

  const confidenceDecomposition = await withRetry(
    async () => {
      const raw = await generateText({
        prompt: buildConfidencePrompt(idea),
        model: config.model,
        signal: config.signal,
      });
      const parsed = JSON.parse(extractJson(raw));
      return ConfidenceDecompositionSchema.parse({
        ideaId,
        ideaTitle: idea.title,
        ...parsed,
      });
    },
    { signal: config.signal }
  );

  // Step 3: Generate counterfactuals
  config.onProgress?.({
    stage: "generating-counterfactuals",
    completedSteps: 2,
    totalSteps: 3,
  });

  const counterfactuals: Counterfactual[] = [];
  for (let i = 0; i < counterfactualCount; i++) {
    if (config.signal?.aborted) break;
    try {
      const cf = await withRetry(
        async () => {
          const raw = await generateText({
            prompt: buildCounterfactualPrompt(idea, i, investigation),
            model: config.model,
            signal: config.signal,
          });
          const parsed = JSON.parse(extractJson(raw));
          return CounterfactualSchema.parse({
            id: `cf-${ideaId}-${i}`,
            ...parsed,
          });
        },
        { signal: config.signal }
      );
      counterfactuals.push(cf);
    } catch {
      // Non-critical: skip counterfactual on failure
    }
  }

  // Capture decision points
  const decisionPoints = angleResults
    ? captureDecisionPoints(
        investigation ?? {
          summary: "",
          keyAspects: [],
          currentState: "",
          challenges: [],
          opportunities: [],
        },
        angleResults
      )
    : [];

  config.onProgress?.({
    stage: "complete",
    completedSteps: 3,
    totalSteps: 3,
  });

  return {
    ideaId,
    ideaTitle: idea.title,
    reasoningChain,
    confidenceDecomposition,
    counterfactuals,
    decisionPoints,
    summary: `Reasoning chain with ${reasoningChain.steps.length} steps (overall confidence: ${(reasoningChain.overallConfidence * 100).toFixed(0)}%). Confidence decomposed across ${confidenceDecomposition.dimensions.length} dimensions. ${counterfactuals.length} counterfactual scenarios analyzed.`,
  };
}

/** Convert an explainability report to markdown. */
export function explainabilityToMarkdown(report: ExplainabilityReport): string {
  const lines: string[] = [
    "# Explainability Report",
    "",
    `**Idea:** ${report.ideaTitle}`,
    `**Overall Confidence:** ${(report.reasoningChain.overallConfidence * 100).toFixed(0)}%`,
    "",
    "## Reasoning Chain",
    "",
  ];

  for (const step of report.reasoningChain.steps) {
    lines.push(
      `${step.stepNumber + 1}. **${step.action}** (confidence: ${(step.confidence * 100).toFixed(0)}%)`
    );
    lines.push(`   ${step.reasoning}`);
    if (step.evidence.length > 0) {
      lines.push(`   Evidence: ${step.evidence.join("; ")}`);
    }
    lines.push("");
  }

  lines.push(
    "## Trigger Aspects",
    "",
    ...report.reasoningChain.triggerAspects.map((a) => `- ${a}`),
    "",
    "## Confidence Decomposition",
    ""
  );

  for (const dim of report.confidenceDecomposition.dimensions) {
    lines.push(
      `- **${dim.dimension}:** ${(dim.score * 100).toFixed(0)}% (weight: ${(dim.weight * 100).toFixed(0)}%) — ${dim.evidence}`
    );
  }

  if (report.counterfactuals.length > 0) {
    lines.push("", "## Counterfactual Analysis", "");
    for (const cf of report.counterfactuals) {
      lines.push(`### ${cf.question}`);
      lines.push(`**Original:** ${cf.originalOutcome}`);
      lines.push(`**If changed:** ${cf.predictedOutcome}`);
      lines.push(
        `**Impact:** ${cf.impactDelta > 0 ? "+" : ""}${(cf.impactDelta * 100).toFixed(0)}% | **Confidence:** ${(cf.confidence * 100).toFixed(0)}%`
      );
      lines.push(`${cf.explanation}`);
      lines.push("");
    }
  }

  return lines.join("\n");
}
