import type { Metadata } from "next";
import { getSession } from "@innovator/core";
import { notFound } from "next/navigation";

interface PageProps {
  params: Promise<{ sessionId: string }>;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { sessionId } = await params;
  if (!sessionId || sessionId.length > 200 || !/^[a-zA-Z0-9_-]+$/.test(sessionId)) {
    return { title: "Session Not Found" };
  }
  const session = getSession(sessionId);
  if (!session) return { title: "Session Not Found" };

  const description = session.investigation?.summary
    ?? `Innovation session exploring "${session.subject}" from ${session.angleResults.length} angles.`;
  const ideaCount = session.angleResults.reduce((sum, ar) => sum + ar.ideas.length, 0);

  return {
    title: `${session.subject} — Innovator`,
    description,
    openGraph: {
      title: `💡 ${session.subject}`,
      description: `${ideaCount} innovation ideas from ${session.angleResults.length} angles. ${description.slice(0, 120)}`,
      type: "article",
      siteName: "Innovator",
    },
    twitter: {
      card: "summary_large_image",
      title: `💡 ${session.subject} — Innovator`,
      description: `${ideaCount} innovation ideas across ${session.angleResults.length} creativity angles`,
    },
  };
}

export default async function SharePage({ params }: PageProps) {
  const { sessionId } = await params;
  if (!sessionId || sessionId.length > 200 || !/^[a-zA-Z0-9_-]+$/.test(sessionId)) {
    notFound();
  }
  const session = getSession(sessionId);
  if (!session) notFound();

  const ideaCount = session.angleResults.reduce((sum, ar) => sum + ar.ideas.length, 0);

  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      <div className="mb-6">
        <h1 className="text-3xl font-bold text-neutral-800 dark:text-neutral-200">
          💡 {session.subject}
        </h1>
        <p className="text-sm text-neutral-500 mt-2">
          {session.angleResults.length} angles · {ideaCount} ideas · {new Date(session.createdAt).toLocaleDateString()}
        </p>
      </div>

      {session.investigation && (
        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3 text-neutral-700 dark:text-neutral-300">Investigation</h2>
          <p className="text-neutral-600 dark:text-neutral-400">{session.investigation.summary}</p>

          {session.investigation.keyAspects.length > 0 && (
            <div className="mt-4 grid gap-2">
              {session.investigation.keyAspects.map((aspect, i) => (
                <div key={i} className="rounded-lg border border-neutral-200 p-3 dark:border-neutral-700">
                  <h3 className="text-sm font-medium text-neutral-800 dark:text-neutral-200">{aspect.title}</h3>
                  <p className="text-xs text-neutral-500 mt-1">{aspect.description}</p>
                </div>
              ))}
            </div>
          )}
        </section>
      )}

      {session.angleResults.map((ar) => (
        <section key={ar.angleId} className="mb-6">
          <h2 className="text-lg font-semibold text-neutral-700 dark:text-neutral-300 mb-3">
            {ar.angleId}
          </h2>
          <div className="grid gap-3">
            {ar.ideas.map((idea, i) => (
              <div key={i} className="rounded-xl border border-neutral-200 p-4 dark:border-neutral-700">
                <h3 className="font-medium text-neutral-800 dark:text-neutral-200">{idea.title}</h3>
                <p className="text-sm text-neutral-600 dark:text-neutral-400 mt-1">{idea.description}</p>
                <div className="flex items-center gap-3 mt-2 text-xs text-neutral-500">
                  <span>Impact: {idea.potentialImpact}</span>
                </div>
              </div>
            ))}
          </div>
        </section>
      ))}

      {session.synthesis && (
        <section className="mt-8 rounded-xl border border-indigo-200 bg-indigo-50 p-5 dark:border-indigo-800 dark:bg-indigo-900/20">
          <h2 className="text-lg font-semibold text-indigo-700 dark:text-indigo-300 mb-2">Synthesis</h2>
          <p className="text-sm text-neutral-700 dark:text-neutral-300">{session.synthesis.recommendation}</p>
          {session.synthesis.themes.length > 0 && (
            <div className="flex flex-wrap gap-2 mt-3">
              {session.synthesis.themes.map((t) => (
                <span key={t} className="rounded-full bg-indigo-100 px-3 py-1 text-xs text-indigo-700 dark:bg-indigo-900/40 dark:text-indigo-300">
                  {t}
                </span>
              ))}
            </div>
          )}
        </section>
      )}

      <footer className="mt-8 pt-4 border-t border-neutral-200 dark:border-neutral-700 text-center text-xs text-neutral-500">
        Generated by <a href="/" className="text-indigo-600 hover:underline">Innovator</a> — AI-Powered Innovation Engine
      </footer>
    </div>
  );
}
