/**
 * @module integrations/confluence
 *
 * Confluence integration — publish innovation reports
 * as Confluence pages using the Confluence REST API v2.
 */

import type { ExportResult } from "./index.js";

export interface ConfluenceConfig {
  apiUrl: string;
  apiToken: string;
  spaceKey: string;
  parentPageId?: string;
}

export interface SynthesisPayload {
  topIdeas: Array<{
    title: string;
    description: string;
    sourceAngle: string;
    potentialImpact: string;
    feasibility: string;
  }>;
  themes: string[];
  recommendation: string;
}

export class ConfluenceIntegration {
  /** Publish a synthesis report as a Confluence page. */
  async publishReport(
    synthesis: SynthesisPayload,
    config: ConfluenceConfig
  ): Promise<ExportResult> {
    const content = this.buildPageContent(synthesis);
    const title = `Innovation Report — ${new Date().toISOString().slice(0, 10)}`;

    try {
      const body: Record<string, unknown> = {
        type: "page",
        title,
        space: { key: config.spaceKey },
        body: {
          storage: {
            value: content,
            representation: "storage",
          },
        },
        ...(config.parentPageId
          ? { ancestors: [{ id: config.parentPageId }] }
          : {}),
      };

      const res = await fetch(`${config.apiUrl}/wiki/rest/api/content`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Basic ${config.apiToken}`,
        },
        body: JSON.stringify(body),
      });

      if (!res.ok) {
        const err = await res.text();
        return {
          success: false,
          error: `Confluence API error: ${err}`,
          integration: "confluence",
        };
      }

      const data = (await res.json()) as {
        id: string;
        _links?: { webui?: string; base?: string };
      };
      const webUrl = data._links?.base && data._links?.webui
        ? `${data._links.base}${data._links.webui}`
        : undefined;

      return {
        success: true,
        externalId: data.id,
        externalUrl: webUrl,
        integration: "confluence",
      };
    } catch (err) {
      return {
        success: false,
        error: err instanceof Error ? err.message : "Confluence publish failed",
        integration: "confluence",
      };
    }
  }

  /** Build Confluence storage format HTML from a synthesis. */
  buildPageContent(synthesis: SynthesisPayload): string {
    const ideaRows = synthesis.topIdeas
      .map(
        (idea) =>
          `<tr>
            <td><strong>${escapeHtml(idea.title)}</strong></td>
            <td>${escapeHtml(idea.description)}</td>
            <td>${escapeHtml(idea.sourceAngle)}</td>
            <td>${escapeHtml(idea.potentialImpact)}</td>
            <td><ac:structured-macro ac:name="status"><ac:parameter ac:name="title">${escapeHtml(idea.feasibility)}</ac:parameter><ac:parameter ac:name="colour">${feasibilityColor(idea.feasibility)}</ac:parameter></ac:structured-macro></td>
          </tr>`
      )
      .join("\n");

    const themesList = synthesis.themes
      .map((t) => `<li>${escapeHtml(t)}</li>`)
      .join("\n");

    return `
<ac:structured-macro ac:name="info"><ac:rich-text-body>
<p>This report was generated by <strong>Innovator AI</strong> on ${new Date().toISOString().slice(0, 10)}.</p>
</ac:rich-text-body></ac:structured-macro>

<h2>Top Ideas</h2>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Source Angle</th>
      <th>Impact</th>
      <th>Feasibility</th>
    </tr>
  </thead>
  <tbody>
    ${ideaRows}
  </tbody>
</table>

<h2>Themes</h2>
<ul>
  ${themesList}
</ul>

<h2>Recommendation</h2>
<p>${escapeHtml(synthesis.recommendation)}</p>
`.trim();
  }
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function feasibilityColor(feasibility: string): string {
  switch (feasibility.toLowerCase()) {
    case "high":
      return "Green";
    case "medium":
      return "Yellow";
    case "low":
      return "Red";
    default:
      return "Grey";
  }
}
