/**
 * @module integrations/slack
 *
 * Slack integration — send notifications, build Block Kit messages,
 * and handle /innovate slash commands.
 */

import type { IdeaExportPayload, ExportResult } from "./index.js";

export interface SlackConfig {
  botToken: string;
  baseUrl?: string;
}

export interface SlashCommandPayload {
  command: string;
  text: string;
  response_url: string;
  user_id: string;
  channel_id: string;
  team_id: string;
}

export class SlackIntegration {
  /** Send a message to a Slack channel. */
  async sendNotification(
    channel: string,
    message: string,
    config: SlackConfig
  ): Promise<ExportResult> {
    const baseUrl = config.baseUrl ?? "https://slack.com/api";

    try {
      const res = await fetch(`${baseUrl}/chat.postMessage`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${config.botToken}`,
        },
        body: JSON.stringify({
          channel,
          text: message,
          unfurl_links: false,
        }),
      });

      if (!res.ok) {
        return {
          success: false,
          error: `Slack API error: ${res.status}`,
          integration: "slack",
        };
      }

      const data = (await res.json()) as { ok: boolean; ts?: string; error?: string };
      if (!data.ok) {
        return {
          success: false,
          error: `Slack error: ${data.error ?? "unknown"}`,
          integration: "slack",
        };
      }

      return {
        success: true,
        externalId: data.ts,
        integration: "slack",
      };
    } catch (err) {
      return {
        success: false,
        error: err instanceof Error ? err.message : "Slack notification failed",
        integration: "slack",
      };
    }
  }

  /** Build Slack Block Kit blocks for a list of ideas. */
  buildIdeaBlocks(ideas: IdeaExportPayload[]): Record<string, unknown>[] {
    const blocks: Record<string, unknown>[] = [
      {
        type: "header",
        text: { type: "plain_text", text: "💡 Innovation Ideas", emoji: true },
      },
      { type: "divider" },
    ];

    for (const idea of ideas) {
      blocks.push({
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*${idea.title}*\n${idea.description}`,
        },
      });

      const fields: { type: string; text: string }[] = [
        { type: "mrkdwn", text: `*Impact:*\n${idea.potentialImpact}` },
      ];

      if (idea.sourceAngle) {
        fields.push({ type: "mrkdwn", text: `*Angle:*\n${idea.sourceAngle}` });
      }
      if (idea.priority) {
        fields.push({ type: "mrkdwn", text: `*Priority:*\n${idea.priority}` });
      }

      blocks.push({ type: "section", fields });

      if (idea.implementationHint) {
        blocks.push({
          type: "context",
          elements: [{ type: "mrkdwn", text: `_Implementation: ${idea.implementationHint}_` }],
        });
      }

      blocks.push({ type: "divider" });
    }

    blocks.push({
      type: "context",
      elements: [{ type: "mrkdwn", text: "_Generated by Innovator AI_ :robot_face:" }],
    });

    return blocks;
  }

  /** Handle a /innovate slash command. Returns a response object for Slack. */
  handleSlashCommand(payload: SlashCommandPayload): {
    response_type: string;
    text: string;
    blocks?: Record<string, unknown>[];
  } {
    const subject = payload.text.trim();

    if (!subject) {
      return {
        response_type: "ephemeral",
        text: "Usage: `/innovate <subject>` — Provide a subject to investigate and generate ideas for.",
      };
    }

    return {
      response_type: "in_channel",
      text: `🔍 Starting innovation pipeline for: *${subject}*`,
      blocks: [
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `🔍 Starting innovation pipeline for: *${subject}*\n_Results will be posted here when ready._`,
          },
        },
        {
          type: "context",
          elements: [{ type: "mrkdwn", text: `Requested by <@${payload.user_id}>` }],
        },
      ],
    };
  }
}
