import type { InnovationIdea } from "@innovator/core/innovation" with {
  "resolution-mode": "import",
};

export interface InnovationProposal {
  title: string;
  body: string;
}

export function generateInnovationProposal(ideas: InnovationIdea[]): InnovationProposal {
  const topIdeas = ideas.slice(0, 5);

  return {
    title: `💡 Innovation Ideas: ${topIdeas[0].title}`,
    body: [
      "## 💡 Innovation Proposal",
      "",
      "Generated by **Innovator AI** — ideas from multiple creativity frameworks.",
      "",
      "### Top Ideas",
      "",
      ...topIdeas
        .map((idea, index) => [
          `#### ${index + 1}. ${idea.title}`,
          "",
          idea.description,
          "",
          `**Potential Impact:** ${idea.potentialImpact}`,
          idea.implementationHint ? `**Implementation:** ${idea.implementationHint}` : "",
          "",
        ])
        .flat(),
      "---",
      "*Generated by [Innovator](https://github.com/josedab/innovator)*",
    ].join("\n"),
  };
}

export function generateInnovationProposalFileName(timestamp: number): string {
  return `innovation-${timestamp}.md`;
}

export function generateInnovationBranchName(timestamp: number): string {
  return `innovation/${timestamp}`;
}
