import type { FailurePattern } from "./types.js";

/** Curated library of 50 canonical innovation failure patterns. */
export const CANONICAL_FAILURE_PATTERNS: FailurePattern[] = [
  // ---- Pivot Failures ----
  {
    id: "pf-01",
    title: "Pivot Too Late",
    category: "pivot-failure",
    description:
      "Organization recognizes the need to pivot but executes too late, losing market window and burning remaining runway.",
    symptoms: [
      "declining metrics ignored for quarters",
      "sunk cost bias in leadership",
      "competitor already occupying target space",
    ],
    rootCause:
      "Emotional attachment to original vision combined with slow decision-making processes.",
    realWorldExamples: [
      "Blockbuster's delayed pivot to streaming",
      "BlackBerry's late smartphone transition",
    ],
    preventionStrategies: [
      "Set kill criteria upfront",
      "Regular pivot/persevere reviews",
      "Track leading indicators not lagging",
    ],
    severity: "critical",
    frequency: "common",
    tags: ["pivot", "timing", "leadership"],
  },
  {
    id: "pf-02",
    title: "Pivot Without Data",
    category: "pivot-failure",
    description:
      "Pivot decision driven by gut feeling or panic rather than validated customer data.",
    symptoms: [
      "no customer interviews conducted",
      "pivot based on single anecdote",
      "team confused about rationale",
    ],
    rootCause: "Lack of systematic customer development process.",
    realWorldExamples: ["Startups pivoting after a single lost deal"],
    preventionStrategies: [
      "Minimum evidence threshold for pivot decisions",
      "Structured experiment design",
    ],
    severity: "high",
    frequency: "common",
    tags: ["pivot", "data", "validation"],
  },
  {
    id: "pf-03",
    title: "Incomplete Pivot",
    category: "pivot-failure",
    description:
      "Half-hearted pivot that keeps too much of the old product while adding new direction, resulting in neither working well.",
    symptoms: [
      "product tries to serve two masters",
      "confused positioning",
      "engineering resources split",
    ],
    rootCause: "Inability to let go of existing customer base or revenue.",
    realWorldExamples: ["Yahoo's scattered product strategy"],
    preventionStrategies: ["Clean break with dedicated team", "Sunset plan for old product"],
    severity: "high",
    frequency: "occasional",
    tags: ["pivot", "focus", "strategy"],
  },
  {
    id: "pf-04",
    title: "Serial Pivoting",
    category: "pivot-failure",
    description: "Repeatedly pivoting without giving any direction enough time to validate.",
    symptoms: ["new strategy every quarter", "team whiplash", "no feature reaches maturity"],
    rootCause: "Impatience combined with unclear success metrics.",
    realWorldExamples: ["Startups with 5+ pivots in 18 months"],
    preventionStrategies: [
      "Minimum validation period per pivot",
      "Clear success metrics before pivoting again",
    ],
    severity: "high",
    frequency: "occasional",
    tags: ["pivot", "patience", "metrics"],
  },

  // ---- Timing Mistakes ----
  {
    id: "tm-01",
    title: "Too Early for Market",
    category: "timing-mistake",
    description: "Technology or product launched before the market is ready to adopt it.",
    symptoms: [
      "low adoption despite good product",
      "excessive customer education needed",
      "infrastructure not yet available",
    ],
    rootCause: "Overestimating market readiness and underestimating adoption barriers.",
    realWorldExamples: ["Apple Newton", "Google Glass v1", "WebTV"],
    preventionStrategies: ["Market readiness assessment", "Staged rollout to early adopters first"],
    severity: "high",
    frequency: "common",
    tags: ["timing", "market", "adoption"],
  },
  {
    id: "tm-02",
    title: "Too Late to Market",
    category: "timing-mistake",
    description: "Entering a market after competitors have established dominant positions.",
    symptoms: ["saturated market", "high customer acquisition costs", "commoditized features"],
    rootCause: "Slow development cycles or delayed market entry decision.",
    realWorldExamples: ["Google+ vs Facebook", "Microsoft Zune vs iPod"],
    preventionStrategies: [
      "Speed-to-market focus",
      "Differentiation strategy required for late entry",
    ],
    severity: "high",
    frequency: "common",
    tags: ["timing", "competition", "speed"],
  },
  {
    id: "tm-03",
    title: "Seasonal Blindspot",
    category: "timing-mistake",
    description: "Launching at the wrong time in the buying cycle for the target market.",
    symptoms: [
      "launch during budget freeze periods",
      "missed conference seasons",
      "holiday timing issues",
    ],
    rootCause: "Insufficient understanding of customer procurement cycles.",
    realWorldExamples: ["B2B launches in December", "Consumer launches missing holiday season"],
    preventionStrategies: ["Map customer buying cycles", "Time launches to industry events"],
    severity: "medium",
    frequency: "occasional",
    tags: ["timing", "sales", "cycles"],
  },
  {
    id: "tm-04",
    title: "Technology Wave Misread",
    category: "timing-mistake",
    description: "Betting on a technology wave that arrives later or differently than expected.",
    symptoms: ["dependencies on immature tech", "partners not ready", "ecosystem gaps"],
    rootCause: "Hype-driven planning instead of infrastructure-readiness analysis.",
    realWorldExamples: ["Early VR companies in 2016", "Blockchain startups in 2017-2018"],
    preventionStrategies: ["Infrastructure dependency mapping", "Phased tech adoption"],
    severity: "high",
    frequency: "common",
    tags: ["timing", "technology", "hype"],
  },

  // ---- Market Misreads ----
  {
    id: "mm-01",
    title: "Solution Looking for Problem",
    category: "market-misread",
    description: "Building technology without a validated customer pain point.",
    symptoms: [
      "cool tech but no buyers",
      "difficulty articulating value proposition",
      "free users but no paying customers",
    ],
    rootCause: "Technology-first thinking without customer development.",
    realWorldExamples: ["Juicero", "Many IoT startups"],
    preventionStrategies: [
      "Problem interviews before solution building",
      "Willingness-to-pay validation",
    ],
    severity: "critical",
    frequency: "very-common",
    tags: ["market", "validation", "problem-fit"],
  },
  {
    id: "mm-02",
    title: "TAM Overestimation",
    category: "market-misread",
    description: "Vastly overestimating the total addressable market size.",
    symptoms: [
      "top-down market sizing only",
      "conflating adjacent markets",
      "assuming high penetration rates",
    ],
    rootCause: "Using industry analyst reports without bottom-up validation.",
    realWorldExamples: ["WeWork's trillion-dollar market claim"],
    preventionStrategies: ["Bottom-up market sizing", "Serviceable market focus"],
    severity: "high",
    frequency: "very-common",
    tags: ["market", "sizing", "TAM"],
  },
  {
    id: "mm-03",
    title: "Customer Segment Confusion",
    category: "market-misread",
    description:
      "Targeting too many customer segments simultaneously without clear primary segment.",
    symptoms: [
      "different features for different segments",
      "diluted messaging",
      "sales team confusion",
    ],
    rootCause: "Fear of missing opportunities by narrowing focus.",
    realWorldExamples: ["Enterprise products trying to also serve SMBs"],
    preventionStrategies: ["Beachhead market strategy", "Sequential segment expansion"],
    severity: "medium",
    frequency: "common",
    tags: ["market", "segments", "focus"],
  },
  {
    id: "mm-04",
    title: "Willingness-to-Pay Gap",
    category: "market-misread",
    description: "Customers want the product but won't pay the required price point.",
    symptoms: [
      "high free-tier usage",
      "conversion rates below 2%",
      "price objection in every sales call",
    ],
    rootCause: "Building before validating pricing model and willingness to pay.",
    realWorldExamples: ["Many freemium products", "Consumer apps with advertising-only models"],
    preventionStrategies: ["Price testing early", "Value metric alignment"],
    severity: "high",
    frequency: "very-common",
    tags: ["market", "pricing", "monetization"],
  },

  // ---- Technical Debt Traps ----
  {
    id: "td-01",
    title: "Premature Architecture",
    category: "technical-debt-trap",
    description: "Over-engineering architecture for scale that may never come.",
    symptoms: [
      "microservices for 100 users",
      "months spent on infrastructure",
      "no product shipped",
    ],
    rootCause: "Engineering perfectionism and resume-driven development.",
    realWorldExamples: ["Startups building Kubernetes clusters before product-market fit"],
    preventionStrategies: [
      "Boring technology choices",
      "Architecture fitness functions",
      "YAGNI principle",
    ],
    severity: "high",
    frequency: "common",
    tags: ["technical", "architecture", "over-engineering"],
  },
  {
    id: "td-02",
    title: "Rewrite Trap",
    category: "technical-debt-trap",
    description:
      "Deciding to rewrite from scratch instead of incrementally improving, losing years of battle-tested code.",
    symptoms: [
      "second system effect",
      "rewrite takes 2-3x longer than estimated",
      "feature parity never achieved",
    ],
    rootCause: "Underestimating the value of existing code and overestimating rewrite benefits.",
    realWorldExamples: ["Netscape's fatal rewrite", "Many internal platform rewrites"],
    preventionStrategies: ["Strangler fig pattern", "Incremental modernization"],
    severity: "critical",
    frequency: "occasional",
    tags: ["technical", "rewrite", "migration"],
  },
  {
    id: "td-03",
    title: "Dependency Avalanche",
    category: "technical-debt-trap",
    description:
      "Accumulating so many dependencies that updates become impossible and security vulnerabilities pile up.",
    symptoms: [
      "thousands of transitive dependencies",
      "can't update without breaking changes",
      "known CVEs in production",
    ],
    rootCause: "Adding dependencies for trivial functionality and never auditing.",
    realWorldExamples: ["left-pad incident", "Log4Shell"],
    preventionStrategies: ["Dependency audit process", "Minimal dependency policy"],
    severity: "high",
    frequency: "common",
    tags: ["technical", "dependencies", "security"],
  },
  {
    id: "td-04",
    title: "Testing Debt Spiral",
    category: "technical-debt-trap",
    description: "Shipping without tests until the codebase is too fragile to safely change.",
    symptoms: ["fear of refactoring", "regression bugs in every release", "manual QA bottleneck"],
    rootCause: "Short-term speed prioritization creating long-term velocity loss.",
    realWorldExamples: ["Legacy enterprise codebases"],
    preventionStrategies: ["Test-driven development", "Coverage gates in CI"],
    severity: "high",
    frequency: "very-common",
    tags: ["technical", "testing", "quality"],
  },

  // ---- Scaling Premature ----
  {
    id: "sp-01",
    title: "Hiring Before PMF",
    category: "scaling-premature",
    description:
      "Rapidly growing the team before product-market fit, burning cash on salaries without revenue.",
    symptoms: [
      "headcount growing faster than revenue",
      "new hires without clear roles",
      "communication overhead exploding",
    ],
    rootCause: "Confusing fundraising success with product-market fit.",
    realWorldExamples: ["Many well-funded startups that failed"],
    preventionStrategies: ["Lean team until PMF validated", "Revenue-based hiring triggers"],
    severity: "critical",
    frequency: "common",
    tags: ["scaling", "hiring", "PMF"],
  },
  {
    id: "sp-02",
    title: "Geographic Over-Expansion",
    category: "scaling-premature",
    description: "Expanding to multiple markets before mastering the first one.",
    symptoms: ["thin presence in many markets", "localization debt", "split management attention"],
    rootCause: "Growth pressure from investors and fear of competition.",
    realWorldExamples: ["Uber's early global expansion challenges", "WeWork international"],
    preventionStrategies: ["Master one market first", "Expansion criteria checklist"],
    severity: "high",
    frequency: "occasional",
    tags: ["scaling", "geography", "focus"],
  },
  {
    id: "sp-03",
    title: "Feature Sprawl Before Depth",
    category: "scaling-premature",
    description: "Adding many features instead of deepening core value proposition.",
    symptoms: ["wide but shallow product", "no feature used by majority", "support burden growing"],
    rootCause: "Responding to every feature request without prioritization framework.",
    realWorldExamples: ["Products becoming bloatware"],
    preventionStrategies: ["Usage-based prioritization", "Feature sunset process"],
    severity: "medium",
    frequency: "very-common",
    tags: ["scaling", "features", "focus"],
  },
  {
    id: "sp-04",
    title: "Infrastructure Gold-Plating",
    category: "scaling-premature",
    description: "Building for million-user scale when you have hundreds of users.",
    symptoms: ["complex distributed systems", "expensive cloud bills", "slow feature delivery"],
    rootCause: "Assuming current growth rate will continue exponentially.",
    realWorldExamples: ["Over-provisioned cloud architectures"],
    preventionStrategies: ["Scale when you feel pain", "Cost-per-user monitoring"],
    severity: "medium",
    frequency: "common",
    tags: ["scaling", "infrastructure", "cost"],
  },

  // ---- Feature Creep ----
  {
    id: "fc-01",
    title: "Kitchen Sink Product",
    category: "feature-creep",
    description: "Product tries to be everything to everyone, losing clarity and usability.",
    symptoms: ["complex UI", "long onboarding", "users only use 10% of features"],
    rootCause: "No clear product vision or inability to say no.",
    realWorldExamples: ["Many enterprise software suites"],
    preventionStrategies: ["Product vision statement", "Feature audit quarterly"],
    severity: "high",
    frequency: "very-common",
    tags: ["features", "focus", "UX"],
  },
  {
    id: "fc-02",
    title: "Competitor Feature Matching",
    category: "feature-creep",
    description: "Reactively copying every competitor feature instead of differentiating.",
    symptoms: [
      "feature comparison spreadsheets driving roadmap",
      "no unique value prop",
      "always playing catch-up",
    ],
    rootCause: "Sales-driven roadmap without strategic product vision.",
    realWorldExamples: ["Browser wars feature bloat"],
    preventionStrategies: ["Differentiation-first strategy", "Customer problem focus"],
    severity: "medium",
    frequency: "common",
    tags: ["features", "competition", "strategy"],
  },
  {
    id: "fc-03",
    title: "Integration Overload",
    category: "feature-creep",
    description: "Building integrations with every possible tool instead of perfecting core ones.",
    symptoms: ["many broken integrations", "maintenance burden", "shallow integration quality"],
    rootCause: "Treating integration count as a competitive metric.",
    realWorldExamples: ["SaaS products with 500+ integrations"],
    preventionStrategies: ["Tier integrations by impact", "API-first approach"],
    severity: "medium",
    frequency: "common",
    tags: ["features", "integrations", "quality"],
  },
  {
    id: "fc-04",
    title: "Configuration Complexity",
    category: "feature-creep",
    description:
      "So many configuration options that the product becomes impossible to set up correctly.",
    symptoms: [
      "multi-page setup wizards",
      "support tickets about configuration",
      "default settings never changed",
    ],
    rootCause: "Making everything configurable instead of making good defaults.",
    realWorldExamples: ["Enterprise software requiring consultants to configure"],
    preventionStrategies: ["Opinionated defaults", "Progressive disclosure"],
    severity: "medium",
    frequency: "common",
    tags: ["features", "configuration", "UX"],
  },

  // ---- Team Misalignment ----
  {
    id: "ta-01",
    title: "Founder Conflict",
    category: "team-misalignment",
    description: "Co-founders diverge on vision, strategy, or values, paralyzing the organization.",
    symptoms: [
      "passive-aggressive decision making",
      "conflicting directives to team",
      "key decisions delayed",
    ],
    rootCause: "Insufficient alignment on vision and values before starting.",
    realWorldExamples: ["Many startup co-founder breakups"],
    preventionStrategies: ["Founder prenup agreements", "Regular vision alignment sessions"],
    severity: "critical",
    frequency: "common",
    tags: ["team", "founders", "alignment"],
  },
  {
    id: "ta-02",
    title: "Culture Debt",
    category: "team-misalignment",
    description:
      "Rapid growth without intentional culture building leads to toxic or dysfunctional culture.",
    symptoms: ["high turnover", "siloed teams", "values only on posters"],
    rootCause: "Treating culture as emergent rather than intentional.",
    realWorldExamples: ["Uber's cultural challenges", "Various tech company culture scandals"],
    preventionStrategies: [
      "Explicit values with behavioral examples",
      "Culture interviews in hiring",
    ],
    severity: "high",
    frequency: "common",
    tags: ["team", "culture", "growth"],
  },
  {
    id: "ta-03",
    title: "Skills Gap Denial",
    category: "team-misalignment",
    description: "Team lacks critical skills but refuses to acknowledge or address the gap.",
    symptoms: ["repeated failures in same area", "NIH syndrome", "resistance to outside help"],
    rootCause: "Pride and fear of admitting weakness.",
    realWorldExamples: ["Engineering teams building their own ML without ML expertise"],
    preventionStrategies: ["Skills matrix assessment", "Strategic hiring or partnerships"],
    severity: "medium",
    frequency: "common",
    tags: ["team", "skills", "learning"],
  },
  {
    id: "ta-04",
    title: "Remote Dysfunction",
    category: "team-misalignment",
    description:
      "Distributed team without proper communication infrastructure, leading to information silos.",
    symptoms: [
      "decisions made in hallway conversations",
      "remote members out of loop",
      "timezone friction",
    ],
    rootCause: "Applying in-office practices to distributed teams.",
    realWorldExamples: ["Many post-COVID remote transitions"],
    preventionStrategies: [
      "Async-first communication",
      "Documentation culture",
      "Timezone overlap policy",
    ],
    severity: "medium",
    frequency: "common",
    tags: ["team", "remote", "communication"],
  },

  // ---- Funding Misjudgment ----
  {
    id: "fm-01",
    title: "Overfunding Complacency",
    category: "funding-misjudgment",
    description: "Raising too much money creates false confidence and wasteful spending.",
    symptoms: [
      "lavish offices before revenue",
      "expensive hires without accountability",
      "extended runway masking problems",
    ],
    rootCause: "Confusing capital raised with value created.",
    realWorldExamples: ["WeWork", "Theranos operational spending"],
    preventionStrategies: ["Lean spending regardless of runway", "Unit economics focus"],
    severity: "high",
    frequency: "occasional",
    tags: ["funding", "spending", "discipline"],
  },
  {
    id: "fm-02",
    title: "Runway Miscalculation",
    category: "funding-misjudgment",
    description:
      "Running out of money before reaching the next milestone, forced into desperate fundraising.",
    symptoms: ["less than 6 months runway", "emergency cost cutting", "desperate pivot"],
    rootCause: "Optimistic revenue projections and underestimated costs.",
    realWorldExamples: ["Countless startups"],
    preventionStrategies: ["Conservative financial modeling", "18-month runway minimum"],
    severity: "critical",
    frequency: "very-common",
    tags: ["funding", "runway", "planning"],
  },
  {
    id: "fm-03",
    title: "Wrong Investor Fit",
    category: "funding-misjudgment",
    description:
      "Taking money from investors whose expectations or involvement style conflicts with company needs.",
    symptoms: ["board conflicts", "pressure for premature scaling", "misaligned exit expectations"],
    rootCause: "Optimizing for valuation rather than investor fit.",
    realWorldExamples: ["Companies forced into premature IPO"],
    preventionStrategies: ["Investor reference checks", "Alignment on timeline and expectations"],
    severity: "high",
    frequency: "occasional",
    tags: ["funding", "investors", "alignment"],
  },

  // ---- Competitive Blindspots ----
  {
    id: "cb-01",
    title: "Incumbent Underestimation",
    category: "competitive-blindspot",
    description: "Assuming incumbents can't or won't respond to disruption.",
    symptoms: [
      "dismissing big company innovation",
      "surprised by fast-follower moves",
      "distribution disadvantage ignored",
    ],
    rootCause: "Innovator's bias — believing disruption is inevitable and incumbents are slow.",
    realWorldExamples: ["Snap vs Instagram Stories", "Many fintech vs banks"],
    preventionStrategies: ["Competitive response modeling", "Distribution advantage analysis"],
    severity: "high",
    frequency: "common",
    tags: ["competition", "incumbents", "disruption"],
  },
  {
    id: "cb-02",
    title: "Indirect Competition Blindspot",
    category: "competitive-blindspot",
    description: "Focusing on direct competitors while ignoring substitutes and alternatives.",
    symptoms: [
      "customers choosing spreadsheets over your product",
      "non-consumption as main competitor",
      "adjacent products absorbing use case",
    ],
    rootCause: "Narrow competitive framing.",
    realWorldExamples: ["CRM tools vs email/spreadsheets", "Many SaaS vs manual processes"],
    preventionStrategies: [
      "Jobs-to-be-done competitive analysis",
      "Include non-consumption in analysis",
    ],
    severity: "medium",
    frequency: "common",
    tags: ["competition", "substitutes", "analysis"],
  },
  {
    id: "cb-03",
    title: "Open Source Disruption",
    category: "competitive-blindspot",
    description: "Commercial product blindsided by open source alternative capturing the market.",
    symptoms: [
      "open source project gaining rapid adoption",
      "community-driven development outpacing commercial",
      "pricing pressure from free alternatives",
    ],
    rootCause: "Underestimating community-driven innovation velocity.",
    realWorldExamples: ["MongoDB vs proprietary databases", "Linux vs Unix"],
    preventionStrategies: ["Open core strategy consideration", "Community engagement"],
    severity: "high",
    frequency: "occasional",
    tags: ["competition", "open-source", "pricing"],
  },

  // ---- Regulatory Oversight ----
  {
    id: "ro-01",
    title: "Regulatory Surprise",
    category: "regulatory-oversight",
    description:
      "Launching without understanding applicable regulations, leading to forced product changes or shutdown.",
    symptoms: ["cease and desist letters", "forced feature removal", "compliance retrofit"],
    rootCause: "Move fast and break things mentality applied to regulated industries.",
    realWorldExamples: ["Uber's regulatory battles", "Crypto exchange shutdowns"],
    preventionStrategies: [
      "Regulatory landscape mapping before launch",
      "Legal review of product features",
    ],
    severity: "critical",
    frequency: "occasional",
    tags: ["regulatory", "compliance", "legal"],
  },
  {
    id: "ro-02",
    title: "Privacy Regulation Gap",
    category: "regulatory-oversight",
    description: "Product data practices violate GDPR, CCPA, or other privacy regulations.",
    symptoms: [
      "no consent management",
      "data stored without purpose limitation",
      "no deletion capability",
    ],
    rootCause: "Treating privacy as an afterthought rather than design principle.",
    realWorldExamples: ["Many companies post-GDPR scramble", "Facebook Cambridge Analytica"],
    preventionStrategies: ["Privacy by design", "Data protection impact assessments"],
    severity: "critical",
    frequency: "common",
    tags: ["regulatory", "privacy", "GDPR"],
  },

  // ---- User Adoption Gap ----
  {
    id: "ua-01",
    title: "Onboarding Cliff",
    category: "user-adoption-gap",
    description: "Users sign up but never complete setup or reach the 'aha moment'.",
    symptoms: [
      "high signup-to-activation drop-off",
      "complex first-run experience",
      "no guided onboarding",
    ],
    rootCause: "Product designed for power users, not first-time experience.",
    realWorldExamples: ["Many developer tools with steep learning curves"],
    preventionStrategies: [
      "Time-to-value optimization",
      "Progressive onboarding",
      "Empty state design",
    ],
    severity: "high",
    frequency: "very-common",
    tags: ["adoption", "onboarding", "UX"],
  },
  {
    id: "ua-02",
    title: "Habit Loop Failure",
    category: "user-adoption-gap",
    description: "Product doesn't create a habit, leading to one-time or infrequent usage.",
    symptoms: ["high churn after trial", "low DAU/MAU ratio", "no natural return trigger"],
    rootCause: "No investment in retention mechanics or natural usage triggers.",
    realWorldExamples: ["Many productivity tools with high churn"],
    preventionStrategies: [
      "Hook model application",
      "Usage trigger design",
      "Value accumulation mechanics",
    ],
    severity: "high",
    frequency: "common",
    tags: ["adoption", "retention", "habits"],
  },
  {
    id: "ua-03",
    title: "Champion Dependency",
    category: "user-adoption-gap",
    description:
      "Product adoption depends on a single champion who eventually leaves or loses influence.",
    symptoms: [
      "usage drops when champion changes roles",
      "no organic spread",
      "single-threaded relationship",
    ],
    rootCause: "Product value not distributed across organization.",
    realWorldExamples: ["Enterprise tools that die when the buyer leaves"],
    preventionStrategies: ["Multi-user value design", "Organizational embedding"],
    severity: "medium",
    frequency: "common",
    tags: ["adoption", "enterprise", "champion"],
  },
  {
    id: "ua-04",
    title: "Network Effect Chicken-and-Egg",
    category: "user-adoption-gap",
    description: "Product requires network effects but can't achieve critical mass.",
    symptoms: [
      "value proposition weak for early users",
      "cold start problem",
      "marketplace imbalance",
    ],
    rootCause: "Launching a network product without seeding strategy.",
    realWorldExamples: ["Many failed social networks and marketplaces"],
    preventionStrategies: [
      "Single-player mode value",
      "Supply-side seeding",
      "Geographic concentration",
    ],
    severity: "high",
    frequency: "common",
    tags: ["adoption", "network-effects", "marketplace"],
  },

  // ---- Integration Breakdown ----
  {
    id: "ib-01",
    title: "API Versioning Nightmare",
    category: "integration-breakdown",
    description: "Breaking API changes destroy ecosystem trust and partner integrations.",
    symptoms: ["partner complaints", "integration maintenance burden", "ecosystem fragmentation"],
    rootCause: "No API versioning strategy or backward compatibility commitment.",
    realWorldExamples: ["Twitter API changes", "Various platform API deprecations"],
    preventionStrategies: [
      "Semantic versioning for APIs",
      "Deprecation policy",
      "Partner communication plan",
    ],
    severity: "high",
    frequency: "occasional",
    tags: ["integration", "API", "ecosystem"],
  },
  {
    id: "ib-02",
    title: "Platform Dependency",
    category: "integration-breakdown",
    description: "Building critical functionality on a platform that changes rules or cuts access.",
    symptoms: [
      "single platform provides majority of users/revenue",
      "no control over distribution",
      "platform policy changes threatening",
    ],
    rootCause: "Over-reliance on a single platform without diversification.",
    realWorldExamples: ["Zynga's Facebook dependency", "Apps affected by App Store policy changes"],
    preventionStrategies: [
      "Platform diversification",
      "Own your distribution channel",
      "Contractual protections",
    ],
    severity: "critical",
    frequency: "occasional",
    tags: ["integration", "platform", "dependency"],
  },
  {
    id: "ib-03",
    title: "Data Silo Creation",
    category: "integration-breakdown",
    description:
      "Product creates data silos that prevent information flow across the organization.",
    symptoms: [
      "manual data export/import",
      "duplicate data entry",
      "inconsistent data across systems",
    ],
    rootCause: "Building without considering the broader data ecosystem.",
    realWorldExamples: ["Departmental SaaS tools creating organizational silos"],
    preventionStrategies: [
      "API-first architecture",
      "Standard data formats",
      "Integration marketplace",
    ],
    severity: "medium",
    frequency: "common",
    tags: ["integration", "data", "interoperability"],
  },

  // ---- Additional Patterns to reach 50 ----
  {
    id: "mm-05",
    title: "Vanity Metrics Delusion",
    category: "market-misread",
    description:
      "Tracking metrics that look impressive but don't correlate with business value or user satisfaction.",
    symptoms: [
      "growing signups but flat revenue",
      "high page views but low engagement",
      "social media followers but no conversions",
    ],
    rootCause: "Choosing metrics that are easy to inflate rather than meaningful to the business.",
    realWorldExamples: [
      "Apps celebrating downloads without tracking retention",
      "Startups reporting registered users not active users",
    ],
    preventionStrategies: [
      "North star metric alignment",
      "Cohort analysis over aggregate metrics",
      "Revenue or retention as primary KPI",
    ],
    severity: "high",
    frequency: "very-common",
    tags: ["market", "metrics", "vanity"],
  },
  {
    id: "td-05",
    title: "Monolith Stagnation",
    category: "technical-debt-trap",
    description:
      "Monolithic codebase grows so large and coupled that any change risks breaking unrelated features.",
    symptoms: [
      "multi-week deployment cycles",
      "every PR requires full regression",
      "new developers take months to become productive",
    ],
    rootCause: "Incremental feature additions without architectural boundaries or modularization.",
    realWorldExamples: ["Large enterprise monoliths", "Legacy banking systems"],
    preventionStrategies: [
      "Module boundary enforcement",
      "Strangler fig decomposition",
      "Feature flag isolation",
    ],
    severity: "high",
    frequency: "common",
    tags: ["technical", "monolith", "modularity"],
  },
  {
    id: "sp-05",
    title: "Channel Proliferation",
    category: "scaling-premature",
    description:
      "Launching on too many sales and distribution channels simultaneously without mastering any.",
    symptoms: [
      "thin presence everywhere",
      "inconsistent brand experience",
      "channel conflict",
      "support team overwhelmed",
    ],
    rootCause:
      "Fear of missing revenue opportunities and pressure to show growth on multiple fronts.",
    realWorldExamples: [
      "Consumer brands spreading across marketplaces",
      "SaaS products listing on every integration directory",
    ],
    preventionStrategies: [
      "Master one channel before expanding",
      "Channel economics analysis",
      "Sequential rollout plan",
    ],
    severity: "medium",
    frequency: "common",
    tags: ["scaling", "channels", "focus"],
  },
  {
    id: "ta-05",
    title: "Tribal Knowledge Trap",
    category: "team-misalignment",
    description:
      "Critical business and technical knowledge exists only in specific people's heads, not documented.",
    symptoms: [
      "bus factor of 1 for critical systems",
      "key person departure causes crisis",
      "onboarding takes forever",
    ],
    rootCause:
      "Rewarding heroics over documentation and treating knowledge sharing as low-priority work.",
    realWorldExamples: [
      "Startups where only the founder knows the infrastructure",
      "Teams where one engineer 'owns' the database",
    ],
    preventionStrategies: [
      "Mandatory documentation sprints",
      "Pair programming rotation",
      "Architecture decision records",
    ],
    severity: "high",
    frequency: "very-common",
    tags: ["team", "knowledge", "documentation"],
  },
  {
    id: "ua-05",
    title: "Premature Gamification",
    category: "user-adoption-gap",
    description:
      "Adding gamification elements (points, badges, leaderboards) before the core value proposition is validated.",
    symptoms: [
      "users game the system rather than derive value",
      "engagement metrics inflate but satisfaction drops",
      "development effort diverted from core features",
    ],
    rootCause: "Confusing engagement mechanics with genuine product value.",
    realWorldExamples: [
      "Enterprise tools with meaningless badges",
      "Health apps with streaks that feel punitive",
    ],
    preventionStrategies: [
      "Validate core value first",
      "Intrinsic motivation before extrinsic",
      "Gamification as enhancement not replacement",
    ],
    severity: "medium",
    frequency: "occasional",
    tags: ["adoption", "gamification", "value"],
  },
  {
    id: "ro-03",
    title: "AI Regulation Blindspot",
    category: "regulatory-oversight",
    description:
      "Building AI-powered products without considering emerging AI-specific regulations and ethical guidelines.",
    symptoms: [
      "no model audit trail",
      "opaque decision-making affecting users",
      "no bias testing process",
      "no human-in-the-loop for high-stakes decisions",
    ],
    rootCause: "Rapid AI adoption outpacing organizational understanding of regulatory trajectory.",
    realWorldExamples: [
      "Facial recognition bans",
      "EU AI Act compliance gaps",
      "Hiring algorithm bias lawsuits",
    ],
    preventionStrategies: [
      "AI ethics review board",
      "Model card documentation",
      "Regular bias audits",
      "Explainability requirements",
    ],
    severity: "critical",
    frequency: "common",
    tags: ["regulatory", "AI", "ethics", "compliance"],
  },
  {
    id: "cb-04",
    title: "Open Source Commoditization",
    category: "competitive-blindspot",
    description:
      "Failing to anticipate that core product functionality will become available as open-source or built-in platform feature.",
    symptoms: [
      "competitors offering similar features for free",
      "cloud providers launching native alternatives",
      "declining differentiation",
    ],
    rootCause:
      "Building a product around functionality rather than around a unique value proposition or data network effect.",
    realWorldExamples: [
      "Many DevOps tools commoditized by cloud providers",
      "Database companies vs cloud-native databases",
    ],
    preventionStrategies: [
      "Build network effects or data moats",
      "Focus on workflow, not individual features",
      "Open core strategy where appropriate",
    ],
    severity: "high",
    frequency: "common",
    tags: ["competition", "commoditization", "open-source", "differentiation"],
  },
];
