import { describe, it, expect, vi } from "vitest";

vi.mock("@github/copilot-sdk", () => ({
  CopilotClient: vi.fn(),
  approveAll: vi.fn(),
}));

import type { Synthesis, InnovationIdea } from "../types.js";
import {
  selectTopIdea,
  generateBranchName,
  generatePRBody,
  buildPRWorkflow,
  innovationToPR,
  workflowToScript,
} from "../innovation-pr/index.js";
import { generateScaffold } from "../scaffolding/index.js";

const mockSynthesis: Synthesis = {
  topIdeas: [
    {
      title: "AI-Powered Code Review Bot",
      description: "An intelligent code review assistant",
      sourceAngle: "cross-domain",
      potentialImpact: "50% faster code reviews",
      feasibility: "high",
    },
    {
      title: "Quantum Testing Framework",
      description: "Test framework using quantum principles",
      sourceAngle: "what-if",
      potentialImpact: "Revolutionary testing",
      feasibility: "low",
    },
  ],
  themes: ["automation", "AI"],
  recommendation: "Focus on AI-powered tools",
};

const mockConfig = {
  owner: "test-org",
  repo: "test-repo",
  baseBranch: "main" as const,
  branchPrefix: "innovation/" as const,
  labels: ["innovation", "auto-generated"] as string[],
  draft: true,
  stack: "typescript" as const,
  license: "MIT" as const,
};

describe("innovation-pr", () => {
  describe("selectTopIdea", () => {
    it("selects highest-feasibility idea", () => {
      const idea = selectTopIdea(mockSynthesis);
      expect(idea).toBeDefined();
      expect(idea!.title).toBe("AI-Powered Code Review Bot");
    });

    it("returns undefined for empty synthesis", () => {
      const empty: Synthesis = { topIdeas: [], themes: [], recommendation: "" };
      expect(selectTopIdea(empty)).toBeUndefined();
    });
  });

  describe("generateBranchName", () => {
    it("creates valid branch name from title", () => {
      const branch = generateBranchName("AI-Powered Code Review Bot");
      expect(branch).toBe("innovation/ai-powered-code-review-bot");
    });

    it("handles special characters", () => {
      const branch = generateBranchName("What's Next? (v2.0)!");
      expect(branch).toMatch(/^innovation\/[a-z0-9-]+$/);
    });

    it("uses custom prefix", () => {
      const branch = generateBranchName("Test Idea", "feature/");
      expect(branch).toMatch(/^feature\//);
    });

    it("truncates long titles", () => {
      const branch = generateBranchName("A".repeat(200));
      expect(branch.length).toBeLessThanOrEqual(80);
    });
  });

  describe("generatePRBody", () => {
    it("generates markdown PR body", () => {
      const idea: InnovationIdea = {
        title: "Test Idea",
        description: "A test description",
        potentialImpact: "High impact",
        implementationHint: "Use TypeScript",
      };
      const scaffold = generateScaffold({ idea });

      const body = generatePRBody(idea, scaffold, mockSynthesis);
      expect(body).toContain("Innovation Idea");
      expect(body).toContain("A test description");
      expect(body).toContain("High impact");
      expect(body).toContain("Strategic Context");
      expect(body).toContain("auto-generated by");
    });
  });

  describe("buildPRWorkflow", () => {
    it("builds complete workflow plan", () => {
      const idea: InnovationIdea = {
        title: "Test Feature",
        description: "Test desc",
        potentialImpact: "Medium",
        implementationHint: "Implement it",
      };

      const plan = buildPRWorkflow(idea, mockConfig);
      expect(plan.branchName).toBe("innovation/test-feature");
      expect(plan.prTitle).toContain("Test Feature");
      expect(plan.commands.length).toBeGreaterThanOrEqual(3);
      expect(plan.commands[0].type).toBe("create-branch");
      expect(plan.commands.some((c) => c.type === "create-pr")).toBe(true);
      expect(Object.keys(plan.files ?? {}).length).toBeGreaterThan(0);
    });

    it("includes reviewer commands when specified", () => {
      const idea: InnovationIdea = {
        title: "Test",
        description: "desc",
        potentialImpact: "high",
        implementationHint: "hint",
      };
      const config = { ...mockConfig, reviewers: ["alice", "bob"] };
      const plan = buildPRWorkflow(idea, config);
      expect(plan.commands.some((c) => c.type === "request-review")).toBe(true);
    });
  });

  describe("innovationToPR", () => {
    it("creates full PR plan from synthesis", () => {
      const result = innovationToPR(mockSynthesis, mockConfig);
      expect(result.status).toBe("planned");
      expect(result.branchName).toContain("innovation/");
      expect(result.filesCreated).toBeGreaterThan(0);
      expect(result.workflowPlan.commands.length).toBeGreaterThan(0);
    });

    it("fails gracefully with empty synthesis", () => {
      const empty: Synthesis = { topIdeas: [], themes: [], recommendation: "" };
      const result = innovationToPR(empty, mockConfig);
      expect(result.status).toBe("failed");
      expect(result.error).toContain("No ideas found");
    });
  });

  describe("workflowToScript", () => {
    it("generates executable shell script", () => {
      const idea: InnovationIdea = {
        title: "Script Test",
        description: "desc",
        potentialImpact: "high",
        implementationHint: "hint",
      };
      const plan = buildPRWorkflow(idea, mockConfig);
      const script = workflowToScript(plan);
      expect(script).toContain("#!/bin/bash");
      expect(script).toContain("set -e");
      expect(script).toContain("innovation/");
      expect(script).toContain("PR workflow complete");
    });
  });
});
