import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "getting-started",
    "core-concepts",
    {
      type: "category",
      label: "Guides",
      items: [
        "guides/web-app",
        "guides/cli",
        "guides/mcp-server",
        "guides/auto-mode",
        "guides/custom-models",
        "guides/artifacts",
        "guides/observatory",
        "guides/events-webhooks",
        "guides/v1-api",
        "guides/bot",
        "guides/provider-setup",
        "guides/copilot-extension",
        "guides/deployment",
      ],
    },
    "api-reference",
    "configuration",
    {
      type: "category",
      label: "API Docs (Generated)",
      items: [{ type: "autogenerated", dirName: "api" }],
    },
    "architecture",
    "troubleshooting",
    "contributing",
  ],
};

export default sidebars;
