/**
 * Session bundle creation, export, import, and sharing.
 */
import type { SessionBundle, SessionMetadata, SessionShareInfo } from "./types.js";
import { SESSION_BUNDLE_VERSION } from "./types.js";

const bundles = new Map<string, SessionBundle>();
const shares = new Map<string, SessionShareInfo>();

/** Create a portable session bundle. */
export function createBundle(
  subject: string,
  data: {
    model?: string;
    anglesUsed?: string[];
    investigation?: Record<string, unknown> | null;
    angleResults?: Array<Record<string, unknown>>;
    synthesis?: Record<string, unknown> | null;
    scores?: Array<Record<string, unknown>>;
    tags?: string[];
    includeHtml?: boolean;
  }
): SessionBundle {
  const id = crypto.randomUUID();
  const now = new Date().toISOString();

  const metadata: SessionMetadata = {
    subject,
    model: data.model,
    anglesUsed: data.anglesUsed ?? [],
    createdAt: now,
    tags: data.tags,
  };

  const bundle: SessionBundle = {
    version: SESSION_BUNDLE_VERSION,
    id,
    exportedAt: now,
    metadata,
    investigation: data.investigation ?? null,
    angleResults: data.angleResults ?? [],
    synthesis: data.synthesis ?? null,
    scores: data.scores ?? [],
  };

  if (data.includeHtml) {
    bundle.renderedHtml = renderBundleHtml(bundle);
  }

  bundles.set(id, bundle);
  return bundle;
}

/** Import a session bundle. Returns the bundle if valid. */
export function importSessionBundle(bundleData: SessionBundle): SessionBundle {
  bundles.set(bundleData.id, bundleData);
  return bundleData;
}

/** Get a bundle by ID. */
export function getBundle(id: string): SessionBundle | null {
  return bundles.get(id) ?? null;
}

/** List all stored bundles. */
export function listBundles(): SessionBundle[] {
  return Array.from(bundles.values()).sort(
    (a, b) => new Date(b.exportedAt).getTime() - new Date(a.exportedAt).getTime()
  );
}

/** Delete a bundle. */
export function deleteBundle(id: string): boolean {
  shares.delete(id);
  return bundles.delete(id);
}

/** Create a shareable link for a bundle with QR code data. */
export function shareBundle(
  bundleId: string,
  baseUrl: string,
  expiresInHours: number = 72
): SessionShareInfo | null {
  const bundle = bundles.get(bundleId);
  if (!bundle) return null;

  const shareUrl = `${baseUrl}/session/${bundleId}`;
  const deepLink = `innovator://session/${bundleId}`;
  const expiresAt = new Date(Date.now() + expiresInHours * 3600_000).toISOString();

  // Generate a simple QR code as SVG data URL
  const qrCodeDataUrl = generateQrSvgDataUrl(shareUrl);

  const share: SessionShareInfo = {
    bundleId,
    shareUrl,
    qrCodeDataUrl,
    deepLink,
    expiresAt,
  };

  shares.set(bundleId, share);
  return share;
}

/** Get share info for a bundle. */
export function getShareInfo(bundleId: string): SessionShareInfo | null {
  return shares.get(bundleId) ?? null;
}

/** Render a bundle as a standalone HTML page. */
function renderBundleHtml(bundle: SessionBundle): string {
  const { metadata, investigation, angleResults, synthesis } = bundle;

  const ideasHtml = angleResults
    .map((result) => {
      const ideas = (result.ideas as Array<{ title?: string; description?: string }>) ?? [];
      return ideas
        .map(
          (idea) => `
        <div style="border:1px solid #e5e7eb;border-radius:8px;padding:16px;margin:8px 0">
          <h4 style="margin:0 0 8px">${idea.title ?? "Untitled"}</h4>
          <p style="margin:0;color:#6b7280">${idea.description ?? ""}</p>
        </div>`
        )
        .join("");
    })
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Innovation Session: ${metadata.subject}</title>
  <style>
    body{font-family:system-ui,-apple-system,sans-serif;max-width:800px;margin:0 auto;padding:20px;color:#1f2937}
    h1{font-size:24px}h2{font-size:18px;margin-top:32px}h3{font-size:16px}
    .meta{color:#6b7280;font-size:14px}.tag{background:#e5e7eb;padding:2px 8px;border-radius:12px;font-size:12px;margin-right:4px}
  </style>
</head>
<body>
  <h1>🔬 ${metadata.subject}</h1>
  <p class="meta">Exported ${bundle.exportedAt} • Model: ${metadata.model ?? "default"}</p>
  <p class="meta">Angles: ${metadata.anglesUsed.join(", ") || "none"}</p>
  ${metadata.tags?.length ? `<p>${metadata.tags.map((t) => `<span class="tag">${t}</span>`).join("")}</p>` : ""}
  ${investigation ? `<h2>📋 Investigation</h2><p>${(investigation as { summary?: string }).summary ?? ""}</p>` : ""}
  <h2>💡 Ideas</h2>
  ${ideasHtml || "<p>No ideas generated yet.</p>"}
  ${synthesis ? `<h2>🔗 Synthesis</h2><p>${JSON.stringify(synthesis).slice(0, 500)}</p>` : ""}
  <hr><p class="meta">Generated by Innovator v${bundle.version}</p>
</body>
</html>`;
}

/** Generate a simple QR-like SVG data URL (placeholder - real QR would use a library). */
function generateQrSvgDataUrl(data: string): string {
  // Simple hash-based pattern as a placeholder for a real QR code library
  const size = 21;
  let hash = 0;
  for (let i = 0; i < data.length; i++) {
    hash = ((hash << 5) - hash + data.charCodeAt(i)) | 0;
  }

  const cells: string[] = [];
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const isFinderPattern =
        (x < 7 && y < 7) || (x >= size - 7 && y < 7) || (x < 7 && y >= size - 7);
      const isData = ((hash >> ((x + y * size) % 31)) & 1) === 1;
      if (isFinderPattern || isData) {
        cells.push(`<rect x="${x * 10}" y="${y * 10}" width="10" height="10" fill="black"/>`);
      }
    }
  }

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size * 10} ${size * 10}">${cells.join("")}</svg>`;
  return `data:image/svg+xml;base64,${Buffer.from(svg).toString("base64")}`;
}
